<?php

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

use Illuminate\Support\Facades\DB;

// Get Biology subject ID
$biology = DB::table('subjects')->where('name', 'BIOLOGY')->first();
if ($biology) {
    echo "Biology subject found with ID: {$biology->id}\n";
    $biologyId = $biology->id;
} else {
    echo "Biology subject not found. Creating it...\n";
    $biologyId = DB::table('subjects')->insertGetId([
        'name' => 'BIOLOGY',
        'created_at' => now(),
        'updated_at' => now(),
    ]);
}

$questions = [
    [
        'question' => 'Which of the following organelles is known as the "powerhouse" of the cell?',
        'a' => 'Nucleus',
        'b' => 'Mitochondrion',
        'c' => 'Ribosome',
        'd' => 'Golgi body',
        'answer' => 'B',
        'explanation' => 'The mitochondrion is where aerobic respiration occurs to produce ATP (energy).',
    ],
    [
        'question' => 'The level of organization of an onion bulb is a/an:',
        'a' => 'Cell',
        'b' => 'Tissue',
        'c' => 'Organ',
        'd' => 'System',
        'answer' => 'C',
        'explanation' => 'An onion bulb consists of several tissues working together, making it an organ.',
    ],
    [
        'question' => 'In a plant cell, the vacuole is mainly used for:',
        'a' => 'Protein synthesis',
        'b' => 'Storage of cell sap',
        'c' => 'Photosynthesis',
        'd' => 'Cell division',
        'answer' => 'B',
        'explanation' => 'The large central vacuole stores water, waste, and nutrients as cell sap.',
    ],
    [
        'question' => 'Which of these organisms is a prokaryote?',
        'a' => 'Amoeba',
        'b' => 'Euglena',
        'c' => 'Bacteria',
        'd' => 'Mushroom',
        'answer' => 'C',
        'explanation' => 'Bacteria belong to Kingdom Monera and lack a defined nucleus.',
    ],
    [
        'question' => 'The movement of Euglena towards light is an example of:',
        'a' => 'Phototropism',
        'b' => 'Phototaxis',
        'c' => 'Photosynthesis',
        'd' => 'Photonasty',
        'answer' => 'B',
        'explanation' => 'Tactic movements (taxis) involve the whole organism moving towards a stimulus.',
    ],
    [
        'question' => 'Which of the following is an autotrophic organism?',
        'a' => 'Rhizopus',
        'b' => 'Spirogyra',
        'c' => 'Tapeworm',
        'd' => 'Mushroom',
        'answer' => 'B',
        'explanation' => 'Spirogyra contains chlorophyll and produces its own food via photosynthesis.',
    ],
    [
        'question' => 'The dental formula of an adult human is:',
        'a' => '2/2, 1/1, 2/2, 3/3',
        'b' => '3/3, 1/1, 4/4, 2/2',
        'c' => '2/2, 0/0, 3/3, 3/3',
        'd' => '1/1, 2/2, 2/2, 3/3',
        'answer' => 'A',
        'explanation' => 'Humans have 2 incisors, 1 canine, 2 premolars, and 3 molars per quadrant.',
    ],
    [
        'question' => 'The end product of protein digestion is:',
        'a' => 'Glucose',
        'b' => 'Fatty acids',
        'c' => 'Amino acids',
        'd' => 'Glycerol',
        'answer' => 'C',
        'explanation' => 'Proteases break down proteins into their building blocks, amino acids.',
    ],
    [
        'question' => 'Which enzyme is responsible for the digestion of starch in the mouth?',
        'a' => 'Pepsin',
        'b' => 'Ptyalin (Salivary Amylase)',
        'c' => 'Trypsin',
        'd' => 'Lipase',
        'answer' => 'B',
        'explanation' => 'Ptyalin starts the chemical breakdown of cooked starch into maltose.',
    ],
    [
        'question' => 'A deficiency of Vitamin C leads to:',
        'a' => 'Rickets',
        'b' => 'Scurvy',
        'c' => 'Beriberi',
        'd' => 'Night blindness',
        'answer' => 'B',
        'explanation' => 'Vitamin C (ascorbic acid) is vital for skin and gum health; deficiency causes scurvy.',
    ],
    [
        'question' => 'The process of maintaining a constant internal environment is called:',
        'a' => 'Respiration',
        'b' => 'Excretion',
        'c' => 'Homeostasis',
        'd' => 'Osmosis',
        'answer' => 'C',
        'explanation' => 'Homeostasis regulates factors like temperature and pH.',
    ],
    [
        'question' => 'Which of these structures is used for gaseous exchange in a fish?',
        'a' => 'Trachea',
        'b' => 'Lungs',
        'c' => 'Gills',
        'd' => 'Stomata',
        'answer' => 'C',
        'explanation' => 'Gills allow fish to extract dissolved oxygen from water.',
    ],
    [
        'question' => 'In humans, deamination of excess amino acids occurs in the:',
        'a' => 'Kidney',
        'b' => 'Liver',
        'c' => 'Pancreas',
        'd' => 'Small intestine',
        'answer' => 'B',
        'explanation' => 'The liver removes nitrogen from amino acids to form urea.',
    ],
    [
        'question' => 'The functional unit of the mammalian kidney is the:',
        'a' => 'Nephridium',
        'b' => 'Flame cell',
        'c' => 'Nephron',
        'd' => 'Ureter',
        'answer' => 'C',
        'explanation' => 'The nephron is responsible for filtration and urine formation.',
    ],
    [
        'question' => 'Which of these is a respiratory organ in an insect?',
        'a' => 'Skin',
        'b' => 'Gills',
        'c' => 'Trachea',
        'd' => 'Lungs',
        'answer' => 'C',
        'explanation' => 'Insects use a system of tracheal tubes for gas exchange.',
    ],
    [
        'question' => 'The tissue responsible for the transport of water in plants is:',
        'a' => 'Phloem',
        'b' => 'Xylem',
        'c' => 'Cambium',
        'd' => 'Cortex',
        'answer' => 'B',
        'explanation' => 'Xylem vessels conduct water and minerals from roots to leaves.',
    ],
    [
        'question' => 'The liquid part of blood that contains nutrients and hormones is:',
        'a' => 'Red blood cells',
        'b' => 'White blood cells',
        'c' => 'Plasma',
        'd' => 'Platelets',
        'answer' => 'C',
        'explanation' => 'Plasma is the fluid medium for transporting dissolved substances.',
    ],
    [
        'question' => 'A person with blood group O is called a universal donor because:',
        'a' => 'They have no antibodies',
        'b' => 'They have no antigens',
        'c' => 'They have both antigens',
        'd' => 'They have A and B antibodies',
        'answer' => 'B',
        'explanation' => 'Group O lacks A and B antigens on red cells, preventing rejection by other groups.',
    ],
    [
        'question' => 'Transpiration is the loss of water vapor through the:',
        'a' => 'Roots',
        'b' => 'Xylem',
        'c' => 'Stomata',
        'd' => 'Phloem',
        'answer' => 'C',
        'explanation' => 'Water vapor escapes mainly through leaf stomata.',
    ],
    [
        'question' => 'The hormone that regulates blood sugar levels is:',
        'a' => 'Adrenaline',
        'b' => 'Thyroxine',
        'c' => 'Insulin',
        'd' => 'Auxin',
        'answer' => 'C',
        'explanation' => 'Insulin, produced by the pancreas, lowers blood glucose levels.',
    ],
    [
        'question' => 'The part of the brain that controls balance and posture is the:',
        'a' => 'Cerebrum',
        'b' => 'Cerebellum',
        'c' => 'Medulla oblongata',
        'd' => 'Thalamus',
        'answer' => 'B',
        'explanation' => 'The cerebellum coordinates voluntary movements and balance.',
    ],
    [
        'question' => 'Which of these is a reflex action?',
        'a' => 'Solving a math problem',
        'b' => 'Blinking when dust enters the eye',
        'c' => 'Writing a letter',
        'd' => 'Driving a car',
        'answer' => 'B',
        'explanation' => 'Reflexes are rapid, involuntary responses to stimuli.',
    ],
    [
        'question' => 'The light-sensitive layer of the mammalian eye is the:',
        'a' => 'Sclera',
        'b' => 'Retina',
        'c' => 'Choroid',
        'd' => 'Cornea',
        'answer' => 'B',
        'explanation' => 'The retina contains photoreceptors (rods and cones) that detect light.',
    ],
    [
        'question' => 'Which plant hormone is responsible for fruit ripening?',
        'a' => 'Auxin',
        'b' => 'Gibberellin',
        'c' => 'Ethylene',
        'd' => 'Cytokinin',
        'answer' => 'C',
        'explanation' => 'Ethylene is a gaseous hormone that triggers fruit ripening.',
    ],
    [
        'question' => 'A support tissue in plants that provides flexibility is:',
        'a' => 'Sclerenchyma',
        'b' => 'Xylem',
        'c' => 'Collenchyma',
        'd' => 'Phloem',
        'answer' => 'C',
        'explanation' => 'Collenchyma provides support to young, growing plant parts.',
    ],
    [
        'question' => 'The type of joint found in the human shoulder is:',
        'a' => 'Hinge joint',
        'b' => 'Ball and socket joint',
        'c' => 'Pivot joint',
        'd' => 'Gliding joint',
        'answer' => 'B',
        'explanation' => 'Ball and socket joints allow movement in many directions.',
    ],
    [
        'question' => 'Asexual reproduction in yeast occurs by:',
        'a' => 'Binary fission',
        'b' => 'Budding',
        'c' => 'Spore formation',
        'd' => 'Fragmentation',
        'answer' => 'B',
        'explanation' => 'Yeast produces small "buds" that eventually detach as new cells.',
    ],
    [
        'question' => 'The part of the flower that develops into a fruit after fertilization is the:',
        'a' => 'Ovule',
        'b' => 'Ovary',
        'c' => 'Stigma',
        'd' => 'Style',
        'answer' => 'B',
        'explanation' => 'The ovary becomes the fruit, while ovules become seeds.',
    ],
    [
        'question' => 'Hypogeal germination is characterized by:',
        'a' => 'The cotyledons remaining below the soil',
        'b' => 'The cotyledons emerging above the soil',
        'c' => 'Fast growth of the hypocotyl',
        'd' => 'Growth in light only',
        'answer' => 'A',
        'explanation' => 'In hypogeal germination (e.g., maize), the epicotyl elongates, keeping cotyledons underground.',
    ],
    [
        'question' => 'Which of the following is a male reproductive organ in plants?',
        'a' => 'Carpel',
        'b' => 'Stamen',
        'c' => 'Style',
        'd' => 'Ovary',
        'answer' => 'B',
        'explanation' => 'The stamen consists of the anther and filament.',
    ],
    [
        'question' => 'The primary source of energy in an ecosystem is:',
        'a' => 'Green plants',
        'b' => 'Decomposition',
        'c' => 'The Sun',
        'd' => 'Herbivores',
        'answer' => 'C',
        'explanation' => 'Solar energy is captured by producers via photosynthesis.',
    ],
    [
        'question' => 'An association where both organisms benefit is called:',
        'a' => 'Parasitism',
        'b' => 'Commensalism',
        'c' => 'Mutualism',
        'd' => 'Predation',
        'answer' => 'C',
        'explanation' => 'Mutualism is a "win-win" symbiotic interaction.',
    ],
    [
        'question' => 'Which of the following is an abiotic factor?',
        'a' => 'Bacteria',
        'b' => 'Temperature',
        'c' => 'Fungi',
        'd' => 'Grass',
        'answer' => 'B',
        'explanation' => 'Abiotic factors are non-living components of an environment.',
    ],
    [
        'question' => 'The process by which nitrogen is returned to the atmosphere is:',
        'a' => 'Nitrogen fixation',
        'b' => 'Nitrification',
        'c' => 'Denitrification',
        'd' => 'Decomposition',
        'answer' => 'C',
        'explanation' => 'Denitrifying bacteria convert nitrates back into nitrogen gas.',
    ],
    [
        'question' => 'A cross between a tall plant (TT) and a short plant (tt) will result in offspring that are all:',
        'a' => 'Tall',
        'b' => 'Short',
        'c' => 'Medium height',
        'd' => '50% tall, 50% short',
        'answer' => 'A',
        'explanation' => 'All offspring (Tt) will show the dominant phenotype (tall).',
    ],
    [
        'question' => 'Sex-linked traits are usually carried on the:',
        'a' => 'Autosomes',
        'b' => 'X chromosome',
        'c' => 'Y chromosome',
        'd' => 'Ribosomes',
        'answer' => 'B',
        'explanation' => 'Most sex-linked traits (like color blindness) are X-linked.',
    ],
    [
        'question' => 'Which of the following describes the physical appearance of an organism?',
        'a' => 'Genotype',
        'b' => 'Phenotype',
        'c' => 'Allele',
        'd' => 'Gamete',
        'answer' => 'B',
        'explanation' => 'Phenotype is the observable expression of a genotype.',
    ],
    [
        'question' => 'The theory of "Survival of the Fittest" was proposed by:',
        'a' => 'Jean Lamarck',
        'b' => 'Charles Darwin',
        'c' => 'Gregor Mendel',
        'd' => 'Robert Hooke',
        'answer' => 'B',
        'explanation' => 'Darwin\'s theory explains evolution through natural selection.',
    ],
    [
        'question' => 'Evidence of evolution from the study of fossils is known as:',
        'a' => 'Comparative anatomy',
        'b' => 'Embryology',
        'c' => 'Paleontology',
        'd' => 'Genetics',
        'answer' => 'C',
        'explanation' => 'Paleontology is the study of prehistoric life through fossils.',
    ],
    [
        'question' => 'An example of a vestigial organ in humans is the:',
        'a' => 'Heart',
        'b' => 'Appendix',
        'c' => 'Liver',
        'd' => 'Kidney',
        'answer' => 'B',
        'explanation' => 'Vestigial organs are structures that have lost their original function over time.',
    ],
        // Additional questions from user (March 7, 2026)
        [
            'question' => 'If a cell with 24 chromosomes undergoes meiosis, how many chromosomes will be present in each daughter cell at the end of Telophase I?',
            'a' => '24',
            'b' => '12',
            'c' => '48',
            'd' => '6',
            'answer' => 'B',
            'explanation' => 'Meiosis I is a reduction division. The chromosome number is halved from diploid (24) to haploid (12) during the first stage.',
        ],
        [
            'question' => 'The organelle responsible for the synthesis of ATP is the mitochondria, but where specifically does the Krebs cycle occur?',
            'a' => 'Inner mitochondrial membrane',
            'b' => 'Mitochondrial matrix',
            'c' => 'Cytoplasm',
            'd' => 'Ribosomes',
            'answer' => 'B',
            'explanation' => 'While the Electron Transport Chain occurs on the cristae (inner membrane), the Krebs cycle takes place in the fluid matrix.',
        ],
        [
            'question' => 'In a DNA molecule, if Cytosine makes up 20% of the bases, what is the percentage of Adenine?',
            'a' => '20%',
            'b' => '80%',
            'c' => '30%',
            'd' => '60%',
            'answer' => 'C',
            'explanation' => 'Based on Chargaff\'s rule (C=G, A=T). If C=20%, G=20% (Total 40%). The remaining 60% must be split equally between A and T, so A=30%.',
        ],
        [
            'question' => 'Which of these is a characteristic of a "test cross"?',
            'a' => 'Crossing two dominant phenotypes',
            'b' => 'Crossing an F1 hybrid with a homozygous dominant parent',
            'c' => 'Crossing an individual of unknown genotype with a homozygous recessive individual',
            'd' => 'Crossing two recessive phenotypes',
            'answer' => 'C',
            'explanation' => 'A test cross determines if a dominant phenotype is homozygous or heterozygous by using a "pure" recessive mate.',
        ],
        [
            'question' => 'The fluidity of the plasma membrane is maintained by the presence of:',
            'a' => 'Glycoproteins',
            'b' => 'Phospholipids only',
            'c' => 'Cholesterol',
            'd' => 'Peripheral proteins',
            'answer' => 'C',
            'explanation' => 'Cholesterol acts as a temperature buffer, preventing the membrane from becoming too rigid or too fluid.',
        ],
        [
            'question' => 'During the light-dependent stage of photosynthesis, "photolysis" of water occurs to provide:',
            'a' => 'Carbon dioxide for the Calvin cycle',
            'b' => 'Oxygen for glucose synthesis',
            'c' => 'Electrons and protons for NADP reduction',
            'd' => 'ATP for the stomata',
            'answer' => 'C',
            'explanation' => 'Water is split to replace electrons in chlorophyll and provide ions to form NADPH.',
        ],
        [
            'question' => 'A plant placed in a hypertonic solution will eventually experience:',
            'a' => 'Turgidity',
            'b' => 'Haemolysis',
            'c' => 'Plasmolysis',
            'd' => 'Flaccidity only',
            'answer' => 'C',
            'explanation' => 'In a high-salt/sugar solution, water leaves the vacuole, causing the cytoplasm to pull away from the cell wall (plasmolysis).',
        ],
        [
            'question' => 'Which of the following tissues is responsible for secondary growth (girth increase) in dicotyledonous stems?',
            'a' => 'Xylem',
            'b' => 'Phloem',
            'c' => 'Vascular Cambium',
            'd' => 'Apical Meristem',
            'answer' => 'C',
            'explanation' => 'Lateral meristems (cambium) cause thickness, whereas apical meristems cause height.',
        ],
        [
            'question' => 'The movement of manufactured food from the leaves to other parts of the plant is called:',
            'a' => 'Transpiration',
            'b' => 'Translocation',
            'c' => 'Guttation',
            'd' => 'Osmosis',
            'answer' => 'B',
            'explanation' => 'Translocation occurs via the phloem; transpiration is the loss of water vapor from leaves.',
        ],
        [
            'question' => 'A unique feature of Bryophytes (like Mosses) that distinguishes them from Pteridophytes (like Ferns) is:',
            'a' => 'Presence of chlorophyll',
            'b' => 'Absence of vascular tissues',
            'c' => 'Production of spores',
            'd' => 'Ability to photosynthesize',
            'answer' => 'B',
            'explanation' => 'Mosses are non-vascular; ferns have xylem and phloem.',
        ],
        [
            'question' => 'In the human heart, the "Pacemaker" is located in the:',
            'a' => 'Left Atrium',
            'b' => 'Right Atrium',
            'c' => 'Left Ventricle',
            'd' => 'Septum',
            'answer' => 'B',
            'explanation' => 'The Sino-atrial (SA) node is located in the upper wall of the right atrium.',
        ],
        [
            'question' => 'During inhalation in mammals, which of the following occurs?',
            'a' => 'Diaphragm relaxes and arches up',
            'b' => 'Ribs move downwards and inwards',
            'c' => 'Thoracic volume increases and pressure decreases',
            'd' => 'External intercostal muscles relax',
            'answer' => 'C',
            'explanation' => 'Increasing the volume of the chest cavity lowers pressure, forcing air into the lungs.',
        ],
        [
            'question' => 'Which blood vessel carries deoxygenated blood from the liver to the heart?',
            'a' => 'Hepatic artery',
            'b' => 'Hepatic vein',
            'c' => 'Hepatic portal vein',
            'd' => 'Pulmonary artery',
            'answer' => 'B',
            'explanation' => 'The hepatic vein carries blood away from the liver toward the Vena Cava. The portal vein carries blood from the gut to the liver.',
        ],
        [
            'question' => 'The "Lub-Dub" sound of the heart is caused by:',
            'a' => 'Contraction of the ventricles',
            'b' => 'Closing of the heart valves',
            'c' => 'Blood rushing through the aorta',
            'd' => 'Relaxation of the atria',
            'answer' => 'B',
            'explanation' => '"Lub" is the closing of AV valves; "Dub" is the closing of semilunar valves.',
        ],
        [
            'question' => 'A person with blood group O is a universal donor because their red blood cells lack:',
            'a' => 'Antibodies A and B',
            'b' => 'Antigens A and B',
            'c' => 'Rhesus factor',
            'd' => 'Haemoglobin',
            'answer' => 'B',
            'explanation' => 'Since they have no antigens on the surface of the RBCs, the recipient\'s antibodies have nothing to attack.',
        ],
        [
            'question' => 'The basic functional unit of the mammalian kidney is the:',
            'a' => 'Nephridium',
            'b' => 'Nephron',
            'c' => 'Neurone',
            'd' => 'Ureter',
            'answer' => 'B',
            'explanation' => 'Be careful not to confuse "Nephron" (kidney) with "Neurone" (nerve).',
        ],
        [
            'question' => 'Ultrafiltration in the kidney occurs in the:',
            'a' => 'Loop of Henle',
            'b' => 'Proximal Convoluted Tubule',
            'c' => 'Bowman’s Capsule',
            'd' => 'Collecting Duct',
            'answer' => 'C',
            'explanation' => 'High pressure in the glomerulus forces small molecules into the Bowman\'s capsule.',
        ],
        [
            'question' => 'Which hormone is responsible for the reabsorption of water in the kidney tubules?',
            'a' => 'Insulin',
            'b' => 'Adrenaline',
            'c' => 'Antidiuretic Hormone (ADH)',
            'd' => 'Thyroxine',
            'answer' => 'C',
            'explanation' => 'ADH (Vasopressin) makes the distal tubule and collecting duct more permeable to water.',
        ],
        [
            'question' => 'The primary nitrogenous waste product of insects is:',
            'a' => 'Ammonia',
            'b' => 'Urea',
            'c' => 'Uric acid',
            'd' => 'Amino acids',
            'answer' => 'C',
            'explanation' => 'Uric acid is less toxic and requires very little water for excretion, aiding survival on land.',
        ],
        [
            'question' => 'Deamination (the breakdown of excess amino acids) occurs in the:',
            'a' => 'Kidney',
            'b' => 'Pancreas',
            'c' => 'Liver',
            'd' => 'Small Intestine',
            'answer' => 'C',
            'explanation' => 'The liver converts the amino group into urea, which is then sent to the kidneys.',
        ],
        [
            'question' => 'Bile is produced in the liver and stored in the gall bladder. Its primary function is to:',
            'a' => 'Digest proteins',
            'b' => 'Emulsify fats',
            'c' => 'Neutralize enzymes',
            'd' => 'Break down starch',
            'answer' => 'B',
            'explanation' => 'Bile breaks large fat globules into tiny droplets (emulsification) to increase the surface area for lipase.',
        ],
        [
            'question' => 'The enzyme "Rennin" is found in the gastric juice of young mammals to:',
            'a' => 'Digest cane sugar',
            'b' => 'Curdle milk protein',
            'c' => 'Break down lipids',
            'd' => 'Activate pepsin',
            'answer' => 'B',
            'explanation' => 'It converts liquid casein into a solid clot so it stays in the stomach long enough to be digested.',
        ],
        [
            'question' => 'Vitamin K is essential for:',
            'a' => 'Good night vision',
            'b' => 'Strong bone formation',
            'c' => 'Blood clotting',
            'd' => 'Energy release',
            'answer' => 'C',
            'explanation' => 'Vitamin K is a cofactor for enzymes involved in the coagulation cascade.',
        ],
        [
            'question' => 'In which part of the gut does the majority of water reabsorption occur?',
            'a' => 'Stomach',
            'b' => 'Duodenum',
            'c' => 'Ileum',
            'd' => 'Large Intestine (Colon)',
            'answer' => 'D',
            'explanation' => 'While the ileum absorbs nutrients, the colon is specialized for water recovery.',
        ],
        [
            'question' => 'The end-product of protein digestion in a termite\'s gut is:',
            'a' => 'Glucose',
            'b' => 'Fatty acids',
            'c' => 'Amino acids',
            'd' => 'Glycerol',
            'answer' => 'C',
            'explanation' => 'Regardless of the organism, the monomer of protein is always an amino acid.',
        ],
        [
            'question' => 'Which of the following is a "biotic" factor in an ecosystem?',
            'a' => 'Soil pH',
            'b' => 'Humidity',
            'c' => 'Decomposers',
            'd' => 'Topography',
            'answer' => 'C',
            'explanation' => 'Biotic factors are living components; the rest are abiotic (non-living).',
        ],
        [
            'question' => 'An association between two organisms where one benefits and the other is neither harmed nor helped is:',
            'a' => 'Parasitism',
            'b' => 'Commensalism',
            'c' => 'Mutualism',
            'd' => 'Saprophytism',
            'answer' => 'B',
            'explanation' => 'Example: Remora fish on a shark.',
        ],
        [
            'question' => 'In a food chain: Grass → Grasshopper → Lizard → Snake, which organism has the least energy available to it?',
            'a' => 'Grass',
            'b' => 'Grasshopper',
            'c' => 'Lizard',
            'd' => 'Snake',
            'answer' => 'D',
            'explanation' => 'Due to the 10% rule, energy is lost at each trophic level; the top predator gets the least.',
        ],
        [
            'question' => 'Succulent stems and reduced leaves are adaptations for plants living in:',
            'a' => 'Freshwater swamps',
            'b' => 'Tropical rainforests',
            'c' => 'Arid deserts',
            'd' => 'Marine habitats',
            'answer' => 'C',
            'explanation' => 'These are xerophytic adaptations to conserve water.',
        ],
        [
            'question' => 'The process by which a bare piece of land is gradually colonized by different communities until a stable state is reached is:',
            'a' => 'Evolution',
            'b' => 'Ecological Succession',
            'c' => 'Natural Selection',
            'd' => 'Eutrophication',
            'answer' => 'B',
            'explanation' => 'Succession starts with pioneer species and ends with a climax community.',
        ],
        [
            'question' => 'Darwin\'s theory of "Natural Selection" is based on the fact that:',
            'a' => 'Acquired traits are inherited',
            'b' => 'Organisms produce more offspring than can survive',
            'c' => 'Mutations are always beneficial',
            'd' => 'All species are fixed',
            'answer' => 'B',
            'explanation' => 'This leads to competition (struggle for existence), where only the "fittest" survive.',
        ],
        [
            'question' => 'Which of these is a "homologous" structure?',
            'a' => 'Wing of a bird and wing of a butterfly',
            'b' => 'Arm of a human and flipper of a whale',
            'c' => 'Eye of an octopus and eye of a human',
            'd' => 'Leg of a spider and leg of a crab',
            'answer' => 'B',
            'explanation' => 'Homologous structures have the same evolutionary origin/anatomy but different functions.',
        ],
        [
            'question' => 'The concept of "Use and Disuse" of organs was proposed by:',
            'a' => 'Charles Darwin',
            'b' => 'Gregor Mendel',
            'c' => 'Jean-Baptiste Lamarck',
            'd' => 'Louis Pasteur',
            'answer' => 'C',
            'explanation' => 'Lamarck believed organisms could pass on traits they strengthened during their lifetime.',
        ],
        [
            'question' => 'Which organism belongs to the Kingdom Monera?',
            'a' => 'Amoeba',
            'b' => 'Bacteria',
            'c' => 'Yeast',
            'd' => 'Euglena',
            'answer' => 'B',
            'explanation' => 'Monerans are prokaryotic (lack a nucleus). Amoeba and Euglena are Protists; Yeast is a Fungus.',
        ],
        [
            'question' => 'The cell wall of a fungus is primarily composed of:',
            'a' => 'Cellulose',
            'b' => 'Chitin',
            'c' => 'Lignin',
            'd' => 'Pectin',
            'answer' => 'B',
            'explanation' => 'Plants use cellulose; fungi use chitin (the same material in insect exoskeletons).',
        ],
        [
            'question' => 'The part of the brain responsible for maintaining posture and balance is the:',
            'a' => 'Cerebrum',
            'b' => 'Cerebellum',
            'c' => 'Medulla Oblongata',
            'd' => 'Hypothalamus',
            'answer' => 'B',
            'explanation' => 'The cerebellum coordinates muscular activity and equilibrium.',
        ],
        [
            'question' => 'A reflex action differs from a voluntary action because it:',
            'a' => 'Involves the brain',
            'b' => 'Is very slow',
            'c' => 'Is automatic and bypasses conscious thought',
            'd' => 'Only involves muscles',
            'answer' => 'C',
            'explanation' => 'Reflexes travel via the reflex arc (spinal cord) for speed.',
        ],
        [
            'question' => 'In the eye, the structure responsible for "Accommodation" (adjusting focus) is the:',
            'a' => 'Retina',
            'b' => 'Iris',
            'c' => 'Ciliary muscle',
            'd' => 'Pupil',
            'answer' => 'C',
            'explanation' => 'Ciliary muscles change the shape of the lens to focus on near or distant objects.',
        ],
        [
            'question' => 'Hypermetropia (long-sightedness) can be corrected using a:',
            'a' => 'Concave lens',
            'b' => 'Convex lens',
            'c' => 'Bifocal lens',
            'd' => 'Cylindrical lens',
            'answer' => 'B',
            'explanation' => 'A convex (converging) lens helps focus light onto the retina rather than behind it.',
        ],
        [
            'question' => 'Which hormone is often called the "Emergency Hormone"?',
            'a' => 'Thyroxine',
            'b' => 'Insulin',
            'c' => 'Adrenaline',
            'd' => 'Estrogen',
            'answer' => 'C',
            'explanation' => 'Adrenaline (Epinephrine) prepares the body for "fight or flight" by increasing heart rate and blood glucose.',
        ],
];

$inserted = 0;
$failed = 0;

foreach ($questions as $index => $q) {
    try {
        DB::table('questions')->insert([
            'subject_id' => $biologyId,
            'question_text' => $q['question'],
            'option_a' => $q['a'],
            'option_b' => $q['b'],
            'option_c' => $q['c'],
            'option_d' => $q['d'],
            'correct_option' => $q['answer'],
            'explanation' => $q['explanation'],
            'difficulty_level' => 'medium',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $inserted++;
        echo "✓ Question " . ($index + 1) . " inserted\n";
    } catch (\Exception $e) {
        $failed++;
        echo "✗ Question " . ($index + 1) . " failed: " . $e->getMessage() . "\n";
    }
}

echo "\n=== SUMMARY ===\n";
echo "Total questions: " . count($questions) . "\n";
echo "Successfully inserted: $inserted\n";
echo "Failed: $failed\n";

// Show total questions in Biology
$total = DB::table('questions')->where('subject_id', $biologyId)->count();
echo "\nTotal Biology questions in database: $total\n";
