<?php

$projectRoot = dirname(__DIR__);
require $projectRoot . '/vendor/autoload.php';

$app = require_once $projectRoot . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Subject;
use App\Models\Question;

$subject = Subject::firstOrCreate(['name' => 'Geography']);

$rows = [
    ['question_text' => 'If the distance between two towns on a map with a scale of 1:50,000 is 4cm, what is the actual ground distance?', 'option_a' => '2 km', 'option_b' => '20 km', 'option_c' => '200 m', 'option_d' => '4 km', 'correct_option' => 'A', 'explanation' => 'Scale 1:50,000 means 1cm = 50,000cm. Since 100,000cm = 1km, then 1cm = 0.5km. Therefore, 4cm = 2km.'],
    ['question_text' => 'Which GIS data source involves the conversion of paper maps into digital format using a cursor?', 'option_a' => 'Remote Sensing', 'option_b' => 'Scanning', 'option_c' => 'Digitizing', 'option_d' => 'Geocoding', 'correct_option' => 'C', 'explanation' => 'Digitizing is the manual process of tracing geographical features from a paper map into a digital vector format.'],
    ['question_text' => 'A map scale is reduced from 1:25,000 to 1:50,000. What happens to the map area?', 'option_a' => 'It is doubled', 'option_b' => 'It is halved', 'option_c' => 'It is reduced to one-quarter', 'option_d' => 'It remains the same', 'correct_option' => 'C', 'explanation' => 'When a linear scale is reduced by half (denominator doubles), the area is reduced by the square of that factor.'],
    ['question_text' => 'In prismatic surveying, the bearing of a line is measured from:', 'option_a' => 'Magnetic North', 'option_b' => 'True North', 'option_c' => 'Grid North', 'option_d' => 'The Equator', 'correct_option' => 'A', 'explanation' => 'Prismatic compasses use a magnetized needle to align with the Earth\'s magnetic field, measuring magnetic bearings.'],
    ['question_text' => 'Which of these is a secondary source of data for a geographer?', 'option_a' => 'Field observation', 'option_b' => 'Interviewing locals', 'option_c' => 'Census reports', 'option_d' => 'Direct measurement', 'correct_option' => 'C', 'explanation' => 'Census reports are pre-collected data by other agencies, making them secondary.'],
    // Batch 2: Questions 11-30
    ['question_text' => 'If a football match starts in London (0°) at 4:00 PM on Saturday, what will be the time and day in a city located on longitude 180°?',
     'option_a' => '4:00 AM, Sunday',
     'option_b' => '4:00 PM, Sunday',
     'option_c' => '4:00 AM, Saturday',
     'option_d' => '6:00 AM, Sunday',
     'correct_option' => 'A',
     'explanation' => '180° difference equals 12 hours. Since the city is East of London, you add 12 hours to 4:00 PM Saturday, which results in 4:00 AM Sunday.'],
    ['question_text' => 'Which of the following processes is primarily responsible for the formation of "Exfoliation Domes" in arid regions?',
     'option_a' => 'Carbonation',
     'option_b' => 'Hydrolysis',
     'option_c' => 'Thermal Expansion',
     'option_d' => 'Oxidation',
     'correct_option' => 'C',
     'explanation' => 'In deserts, extreme temperature changes cause the outer layers of rocks to expand and contract, eventually peeling off like onion skins.'],
    ['question_text' => 'A traveler moving from the Equator toward the North Pole will notice that the vegetation changes in which specific order?',
     'option_a' => 'Tropical Rainforest → Savanna → Desert → Mediterranean',
     'option_b' => 'Savanna → Tropical Rainforest → Desert → Tundra',
     'option_c' => 'Tropical Rainforest → Desert → Savanna → Taiga',
     'option_d' => 'Desert → Savanna → Tropical Rainforest → Mediterranean',
     'correct_option' => 'A',
     'explanation' => 'Vegetation follows climatic belts; moving North from the wet Equator takes you through the drying Savanna, the arid Desert, and then the temperate Mediterranean zone.'],
    ['question_text' => 'In a settlement showing a "Linear" pattern, the most likely factor influencing its shape is the presence of:',
     'option_a' => 'A central market square',
     'option_b' => 'A fertile volcanic plain',
     'option_c' => 'A major transportation route',
     'option_d' => 'A defensive hilltop',
     'correct_option' => 'C',
     'explanation' => 'Linear settlements develop along narrow routes like roads, railways, or river banks where access to transport is primary.'],
    ['question_text' => 'Which of these atmospheric conditions is most likely to lead to the formation of "Smog" in industrial cities?',
     'option_a' => 'High wind velocity',
     'option_b' => 'Temperature Inversion',
     'option_c' => 'Convectional rainfall',
     'option_d' => 'High relative humidity',
     'correct_option' => 'B',
     'explanation' => 'Temperature inversion traps cold air (and pollutants) near the ground under a layer of warm air, preventing smoke from dispersing.'],
    ['question_text' => 'A map has a scale of 1:50,000. If the distance between two villages on the map is 10cm, what is the actual ground distance?',
     'option_a' => '0.5km',
     'option_b' => '5km',
     'option_c' => '50km',
     'option_d' => '500km',
     'correct_option' => 'B',
     'explanation' => 'Using the formula: Ground Distance = Map Distance × Scale Denominator. Since 10 cm × 50,000 = 500,000 cm = 5 km.'],
    ['question_text' => 'Which of the following is an "Internal Force" that shapes the Earth\'s crust?',
     'option_a' => 'Denudation',
     'option_b' => 'Weathering',
     'option_c' => 'Vulcanicity',
     'option_d' => 'Deposition',
     'correct_option' => 'C',
     'explanation' => 'Vulcanicity (volcanism) originates from within the Earth (endogenic), whereas the others are exogenic (external) forces.'],
    ['question_text' => 'The "Great Circle" route is preferred in long-distance aviation because it:',
     'option_a' => 'Avoids turbulent weather zones',
     'option_b' => 'Follows the lines of constant compass bearing',
     'option_c' => 'Represents the shortest distance between two points',
     'option_d' => 'Always stays within the same time zone',
     'correct_option' => 'C',
     'explanation' => 'A Great Circle is the shortest path between two points on a sphere, saving fuel and time for international flights.'],
    ['question_text' => 'Calculate the range of temperature for a station where the highest monthly temperature is 32°C and the lowest is 18°C.',
     'option_a' => '50°C',
     'option_b' => '25°C',
     'option_c' => '14°C',
     'option_d' => '10°C',
     'correct_option' => 'C',
     'explanation' => 'Temperature range is the difference between the maximum and minimum values (32 - 18 = 14°C).'],
    ['question_text' => 'Which soil type is most associated with the "Leaching" process in heavy rainfall areas like the Niger Delta?',
     'option_a' => 'Chernozem',
     'option_b' => 'Latosols (Laterites)',
     'option_c' => 'Podzols',
     'option_d' => 'Alluvial soils',
     'correct_option' => 'B',
     'explanation' => 'Heavy rain washes away nutrients (leaching), leaving behind iron and aluminum oxides that form reddish, acidic Laterite soils.'],
    ['question_text' => 'The primary reason why the population density of the Nile Valley is high despite being in a desert is:',
     'option_a' => 'Presence of mineral resources',
     'option_b' => 'Availability of water for irrigation',
     'option_c' => 'Absence of pests and diseases',
     'option_d' => 'Favorable cool climate',
     'correct_option' => 'B',
     'explanation' => 'The Nile River provides a permanent water source in an arid region, allowing for intensive agriculture.'],
    ['question_text' => 'What is the primary difference between a "Cuesta" and a "Hogback"?',
     'option_a' => 'The type of rock they are made of',
     'option_b' => 'The altitude above sea level',
     'option_c' => 'The angle of the dip slope',
     'option_d' => 'The presence of vegetation',
     'correct_option' => 'C',
     'explanation' => 'A Cuesta has one steep side and one gentle slope, while a Hogback has two equally steep sides due to a very high angle of dip.'],
    ['question_text' => 'In the theory of "Demographic Transition," a country with a high birth rate and a rapidly falling death rate is in:',
     'option_a' => 'Stage 1',
     'option_b' => 'Stage 2',
     'option_c' => 'Stage 3',
     'option_d' => 'Stage 4',
     'correct_option' => 'B',
     'explanation' => 'Stage 2 (Early Expanding) is characterized by high fertility and improving healthcare, leading to a population explosion.'],
    ['question_text' => 'Which of the following ocean currents is responsible for the fog and dry conditions along the coast of Namibia?',
     'option_a' => 'The Gulf Stream',
     'option_b' => 'The Benguela Current',
     'option_c' => 'The Canary Current',
     'option_d' => 'The Kuroshio Current',
     'correct_option' => 'B',
     'explanation' => 'The cold Benguela current cools the air above it, preventing rain and causing the formation of the Namib Desert.'],
    ['question_text' => 'The term "Karst Topography" is specifically used to describe landscapes formed in:',
     'option_a' => 'Granite rocks',
     'option_b' => 'Basaltic plateaus',
     'option_c' => 'Limestone regions',
     'option_d' => 'Sandstone ridges',
     'correct_option' => 'C',
     'explanation' => 'Karst refers to areas where the bedrock is carbonate (limestone), leading to features like sinkholes and caves through chemical weathering.'],
    ['question_text' => 'Which of the following is a "Non-renewable" natural resource?',
     'option_a' => 'Timber',
     'option_b' => 'Solar energy',
     'option_c' => 'Petroleum',
     'option_d' => 'Water',
     'correct_option' => 'C',
     'explanation' => 'Petroleum takes millions of years to form; once extracted and used, it cannot be replaced in a human timeframe.'],
    ['question_text' => 'What happens to the temperature of a parcel of air as it rises up a mountain side?',
     'option_a' => 'It increases due to pressure',
     'option_b' => 'It remains constant',
     'option_c' => 'It decreases at the adiabatic lapse rate',
     'option_d' => 'It increases due to proximity to the sun',
     'correct_option' => 'C',
     'explanation' => 'As air rises, it expands and cools. This is known as the Adiabatic Lapse Rate (approx. 6.5°C per 1,000m).'],
    ['question_text' => 'An environmental hazard common in the Sahel region of Nigeria is:',
     'option_a' => 'Oil spillage',
     'option_b' => 'Gully erosion',
     'option_c' => 'Desertification',
     'option_d' => 'Tropical cyclones',
     'correct_option' => 'C',
     'explanation' => 'The Sahel is the semi-arid transition zone where overgrazing and climate change lead to the southward encroachment of the desert.'],
    ['question_text' => 'Which type of fishing is most common in the shallow waters of the "Continental Shelf"?',
     'option_a' => 'Deep-sea trawling',
     'option_b' => 'Subsistence fishing',
     'option_c' => 'Inshore fishing',
     'option_d' => 'Sport fishing',
     'correct_option' => 'C',
     'explanation' => 'The Continental Shelf is rich in plankton and sunlight, making it the most productive area for commercial inshore fishing.'],
    ['question_text' => 'The main factor responsible for the high salinity of the Dead Sea is:',
     'option_a' => 'Excessive rainfall',
     'option_b' => 'High rate of evaporation and lack of outlets',
     'option_c' => 'Proximity to the Equator',
     'option_d' => 'Large number of rivers flowing into it',
     'correct_option' => 'B',
     'explanation' => 'In closed basins with high heat, water evaporates leaving salt behind, and because there is no outlet to the ocean, the concentration stays high.'],
    // Batch 3: Questions 31-50
    ['question_text' => 'If the RF (Representative Fraction) of a map is 1:100,000, what is the statement scale?',
     'option_a' => '1cm to 1km',
     'option_b' => '1cm to 10km',
     'option_c' => '1cm to 100km',
     'option_d' => '2cm to 1km',
     'correct_option' => 'A',
     'explanation' => '1:100,000 means 100,000 cm on ground = 1 cm on map. Therefore, 1cm on the map represents 1km on the ground.'],
    ['question_text' => 'A "U-Shaped Valley" is a landform created by the action of:',
     'option_a' => 'Running water',
     'option_b' => 'Wind erosion',
     'option_c' => 'Glacial erosion',
     'option_d' => 'Marine waves',
     'correct_option' => 'C',
     'explanation' => 'Glaciers are bulky and "bulldoze" V-shaped river valleys into wide, flat-bottomed U-shaped valleys.'],
    ['question_text' => 'The "Gutenberg Discontinuity" separates which two layers of the Earth?',
     'option_a' => 'Crust and Mantle',
     'option_b' => 'Upper Mantle and Lower Mantle',
     'option_c' => 'Mantle and Core',
     'option_d' => 'Inner Core and Outer Core',
     'correct_option' => 'C',
     'explanation' => 'The Moho separates the Crust/Mantle, while the Gutenberg separates the Mantle/Core.'],
    ['question_text' => 'Which of the following is a "Tertiary" economic activity?',
     'option_a' => 'Iron ore mining',
     'option_b' => 'Textile manufacturing',
     'option_c' => 'Banking and Finance',
     'option_d' => 'Cattle rearing',
     'correct_option' => 'C',
     'explanation' => 'Tertiary activities are service-based (Banking, Teaching, Tourism), while Primary is raw material extraction and Secondary is manufacturing.'],
    ['question_text' => 'The Mediterranean climate is characterized by:',
     'option_a' => 'Hot, wet summers and cold, dry winters',
     'option_b' => 'Hot, dry summers and mild, wet winters',
     'option_c' => 'Rainfall throughout the year',
     'option_d' => 'Extreme cold throughout the year',
     'correct_option' => 'B',
     'explanation' => 'This is a unique climate found around the Mediterranean Sea and parts of South Africa/California where rain falls in winter.'],
    ['question_text' => 'Which of the following planets has the shortest period of revolution around the sun?',
     'option_a' => 'Earth',
     'option_b' => 'Mars',
     'option_c' => 'Mercury',
     'option_d' => 'Venus',
     'correct_option' => 'C',
     'explanation' => 'Mercury is closest to the sun and travels the shortest orbital path at the highest speed.'],
    ['question_text' => 'The process by which plants release water vapor into the atmosphere is:',
     'option_a' => 'Evaporation',
     'option_b' => 'Condensation',
     'option_c' => 'Transpiration',
     'option_d' => 'Precipitation',
     'correct_option' => 'C',
     'explanation' => 'Transpiration is specifically the loss of water through the stomata of plant leaves.'],
    ['question_text' => '"Plucking" and "Abrasion" are erosional processes associated with:',
     'option_a' => 'Wind',
     'option_b' => 'Ice',
     'option_c' => 'Waves',
     'option_d' => 'Rivers',
     'correct_option' => 'B',
     'explanation' => 'Plucking occurs when ice freezes onto rock and pulls it away; abrasion is the grinding of that rock against the valley floor.'],
    ['question_text' => 'Which of these scales is the "Largest"?',
     'option_a' => '1:25,000',
     'option_b' => '1:50,000',
     'option_c' => '1:100,000',
     'option_d' => '1:250,000',
     'correct_option' => 'A',
     'explanation' => 'In map scales, the smaller the denominator, the "larger" the scale (it shows more detail of a smaller area).'],
    ['question_text' => 'The "Solar Solstice" around June 21st means the sun is vertically overhead at the:',
     'option_a' => 'Equator',
     'option_b' => 'Tropic of Cancer',
     'option_c' => 'Tropic of Capricorn',
     'option_d' => 'Arctic Circle',
     'correct_option' => 'B',
     'explanation' => 'During the Summer Solstice (Northern Hemisphere), the sun is directly above 23.5°N (Tropic of Cancer).'],
    ['question_text' => 'A major problem facing rail transport in Africa is:',
     'option_a' => 'Lack of passengers',
     'option_b' => 'Different track gauges',
     'option_c' => 'High speed of trains',
     'option_d' => 'Short distances between cities',
     'correct_option' => 'B',
     'explanation' => 'Colonial powers built railways with different widths (gauges), making it difficult to link different national rail systems.'],
    ['question_text' => 'In the "Concentric Zone Model" of city structure, the center is occupied by the:',
     'option_a' => 'Commuter zone',
     'option_b' => 'Low-class residential',
     'option_c' => 'Central Business District (CBD)',
     'option_d' => 'Industrial zone',
     'correct_option' => 'C',
     'explanation' => 'The CBD is the core of the city where commercial activity is highest.'],
    ['question_text' => 'Which of the following is a "Fold Mountain"?',
     'option_a' => 'The Drakensberg',
     'option_b' => 'The Himalayas',
     'option_c' => 'Mt. Kilimanjaro',
     'option_d' => 'The Sierra Nevada',
     'correct_option' => 'B',
     'explanation' => 'The Himalayas were formed by the collision of the Indian and Eurasian plates, folding the crust upward.'],
    ['question_text' => '"Relative Humidity" is measured using a:',
     'option_a' => 'Barometer',
     'option_b' => 'Hydrometer',
     'option_c' => 'Hygrometer',
     'option_d' => 'Anemometer',
     'correct_option' => 'C',
     'explanation' => 'A Wet and Dry bulb thermometer (Hygrometer) is used to calculate the percentage of moisture in the air.'],
    ['question_text' => 'Which of these clouds is associated with thunderstorms and heavy rain?',
     'option_a' => 'Cirrus',
     'option_b' => 'Stratus',
     'option_c' => 'Cumulonimbus',
     'option_d' => 'Altocumulus',
     'correct_option' => 'C',
     'explanation' => 'Cumulonimbus are towering vertical clouds often called "thunderheads."'],
    ['question_text' => 'The transition zone between two different ecosystems is called an:',
     'option_a' => 'Ecotone',
     'option_b' => 'Ecological niche',
     'option_c' => 'Abiotic factor',
     'option_d' => 'Biome',
     'correct_option' => 'A',
     'explanation' => 'An ecotone (like a marsh between land and lake) contains species from both systems.'],
    ['question_text' => 'The main cause of "Earth Tides" is the:',
     'option_a' => 'Rotation of the Earth',
     'option_b' => 'Gravitational pull of the Moon and Sun',
     'option_c' => 'Shifting of tectonic plates',
     'option_d' => 'Ocean currents',
     'correct_option' => 'B',
     'explanation' => 'The moon\'s gravity pulls on the Earth\'s waters, creating high and low tides.'],
    ['question_text' => 'Which of the following is a "Secondary" rock?',
     'option_a' => 'Basalt',
     'option_b' => 'Gneiss',
     'option_c' => 'Sandstone',
     'option_d' => 'Gabbro',
     'correct_option' => 'C',
     'explanation' => 'Sedimentary rocks (like sandstone) are considered "secondary" because they are formed from the debris of pre-existing rocks.'],
    ['question_text' => 'In Nigeria, the "Harmattan" wind blows from the:',
     'option_a' => 'South-West',
     'option_b' => 'North-East',
     'option_c' => 'South-East',
     'option_d' => 'North-West',
     'correct_option' => 'B',
     'explanation' => 'The North-East Trade Winds blow from the Sahara Desert, bringing dust and dry conditions.'],
    ['question_text' => 'The "Prime Meridian" passes through which of these cities?',
     'option_a' => 'New York',
     'option_b' => 'Accra',
     'option_c' => 'Cairo',
     'option_d' => 'Lagos',
     'correct_option' => 'B',
     'explanation' => 'The 0° longitude line passes through Greenwich (London) and Accra (Ghana).'],
];

// Additional questions from user (March 7, 2026)
$rows = array_merge($rows, [
    [
        'question_text' => 'If the bearing of point A from point B is X°, what is the bearing of B from A?',
        'option_a' => 'X°',
        'option_b' => 'X° + 90°',
        'option_c' => 'X° + 180°',
        'option_d' => 'X° - 90°',
        'correct_option' => 'C',
        'explanation' => 'To find a back-bearing, if the forward bearing is X°, add 180°.'
    ],
    [
        'question_text' => 'Calculate the local time at Longitude 75°W when it is 10:00 AM at the Prime Meridian (0°).',
        'option_a' => '5:00 AM',
        'option_b' => '3:00 PM',
        'option_c' => '5:00 PM',
        'option_d' => '8:00 AM',
        'correct_option' => 'A',
        'explanation' => '75°/15 = 5 hours. Since it is West, we subtract: 10:00 AM - 5 hours = 5:00 AM.'
    ],
    [
        'question_text' => 'A map scale is 1:100,000. If a forest covers 4 cm² on this map, what is its actual area on the ground?',
        'option_a' => '4 km²',
        'option_b' => '40 km²',
        'option_c' => '16 km²',
        'option_d' => '8 km²',
        'correct_option' => 'A',
        'explanation' => 'Linear scale is 1cm = 1km. Areal scale is (1cm)² = (1km)². Thus, 4 cm² = 4 km².'
    ],
    [
        'question_text' => 'Which statistical diagram is most suitable for showing the components of a total population (e.g., age groups) in a single year?',
        'option_a' => 'Dot map',
        'option_b' => 'Pie chart',
        'option_c' => 'Line graph',
        'option_d' => 'Isopleth',
        'correct_option' => 'B',
        'explanation' => 'Pie charts effectively show the proportion of various components that make up a whole.'
    ],
    [
        'question_text' => 'The vertical distance between the highest and lowest points in a given area is known as:',
        'option_a' => 'Vertical Interval',
        'option_b' => 'Gradient',
        'option_c' => 'Relative Relief',
        'option_d' => 'Aspect',
        'correct_option' => 'C',
        'explanation' => 'Relative relief measures local height variation, whereas V.I. is specific to contour lines on a map.'
    ],
    [
        'question_text' => "The 'Gutenberg Discontinuity' separates which two layers?",
        'option_a' => 'Crust and Mantle',
        'option_b' => 'Mantle and Outer Core',
        'option_c' => 'Inner and Outer Core',
        'option_d' => 'Sial and Sima',
        'correct_option' => 'B',
        'explanation' => 'This boundary marks the point where seismic S-waves stop, indicating a transition from solid mantle to liquid core.'
    ],
    [
        'question_text' => "A 'knickpoint' is a feature associated with:",
        'option_a' => 'River rejuvenation',
        'option_b' => 'Glacial deposition',
        'option_c' => 'Wind abrasion',
        'option_d' => 'Coastal submergence',
        'correct_option' => 'A',
        'explanation' => 'Rejuvenation (a drop in sea level) causes a river to cut back into its bed, creating a sharp break in the profile called a knickpoint.'
    ],
    [
        'question_text' => 'Which rock type is formed from the cooling of magma but lacks crystals due to extremely rapid cooling?',
        'option_a' => 'Granite',
        'option_b' => 'Basalt',
        'option_c' => 'Obsidian',
        'option_d' => 'Gabbro',
        'correct_option' => 'C',
        'explanation' => 'Obsidian is volcanic glass; it cools so fast that atoms cannot arrange into a crystalline structure.'
    ],
    [
        'question_text' => "The 'Great Rift Valley' of East Africa was formed primarily by:",
        'option_a' => 'Folding',
        'option_b' => 'Faulting (Tension)',
        'option_c' => 'Volcanic eruption',
        'option_d' => 'Glacial gouging',
        'correct_option' => 'B',
        'explanation' => 'It is a graben formed by the pulling apart of tectonic plates (tensional forces).'
    ],
    [
        'question_text' => "The 'Horse Latitudes' are characterized by:",
        'option_a' => 'Heavy rainfall and low pressure',
        'option_b' => 'High pressure and calm winds',
        'option_c' => 'Cyclonic activity',
        'option_d' => 'Strong trade winds',
        'correct_option' => 'B',
        'explanation' => 'Located at 30° N/S, these are subtropical high-pressure belts where air sinks, causing dry, calm conditions.'
    ],
    [
        'question_text' => 'Which cloud type is most responsible for heavy thunderstorms and hailstones?',
        'option_a' => 'Cirrus',
        'option_b' => 'Stratus',
        'option_c' => 'Cumulonimbus',
        'option_d' => 'Altocumulus',
        'correct_option' => 'C',
        'explanation' => 'These are massive vertical clouds often called "thunderheads."'
    ],
    [
        'question_text' => "The 'Rain Shadow' effect is most associated with which type of rainfall?",
        'option_a' => 'Convectional',
        'option_b' => 'Cyclonic',
        'option_c' => 'Orographic',
        'option_d' => 'Frontal',
        'correct_option' => 'C',
        'explanation' => 'Orographic (relief) rain occurs when mountains force air upward; the leeward side remains dry (rain shadow).'
    ],
    [
        'question_text' => "In the 'Koppen Climate Classification', the letter 'f' (e.g., Af) stands for:",
        'option_a' => 'Frequently dry',
        'option_b' => 'Forest vegetation',
        'option_c' => 'No dry season',
        'option_d' => 'High humidity',
        'correct_option' => 'C',
        'explanation' => "'f' comes from the German feucht (moist), indicating precipitation throughout the year."
    ],
    [
        'question_text' => 'Which soil order is commonly found in semi-arid regions and contains high levels of calcium?',
        'option_a' => 'Oxisols',
        'option_b' => 'Pedocals',
        'option_c' => 'Pedalfers',
        'option_d' => 'Podzols',
        'correct_option' => 'B',
        'explanation' => 'Pedocals are typical of dry climates where evaporation exceeds precipitation, leading to calcium carbonate accumulation.'
    ],
    [
        'question_text' => "The 'Montreal Protocol' was an international agreement designed to:",
        'option_a' => 'Reduce CO2 emissions',
        'option_b' => 'Protect the ozone layer',
        'option_c' => 'Stop desertification',
        'option_d' => 'Regulate international trade in ivory',
        'correct_option' => 'B',
        'explanation' => 'It phased out the production of CFCs that deplete the ozone layer.'
    ],
    [
        'question_text' => 'The location of the Iron and Steel industry at Ajakuta, Nigeria, is primarily due to:',
        'option_a' => 'Market proximity',
        'option_b' => 'Availability of Iron Ore at Itakpe',
        'option_c' => 'Proximity to the sea',
        'option_d' => 'High population density',
        'correct_option' => 'B',
        'explanation' => 'Heavy industries are typically "resource-oriented" to minimize transport costs of bulky raw materials.'
    ],
    [
        'question_text' => "A 'Primate City' is one that:",
        'option_a' => 'Is the oldest city in a country',
        'option_b' => 'Is more than twice as large as the second-largest city',
        'option_c' => 'Performs only religious functions',
        'option_d' => 'Has a declining population',
        'correct_option' => 'B',
        'explanation' => 'Proposed by Mark Jefferson, it describes a city that dominates the urban hierarchy in size and influence.'
    ],
    [
        'question_text' => 'Which mode of transport is most suitable for transporting bulky, low-value goods over very long distances?',
        'option_a' => 'Air',
        'option_b' => 'Road',
        'option_c' => 'Water',
        'option_d' => 'Pipeline',
        'correct_option' => 'C',
        'explanation' => 'Water transport has the highest capacity and lowest cost per unit for heavy/bulky cargo.'
    ],
    [
        'question_text' => 'The Demographic Transition Model suggests that in Stage 2:',
        'option_a' => 'Both birth and death rates are high',
        'option_b' => 'Birth rates are high while death rates fall rapidly',
        'option_c' => 'Population begins to decline',
        'option_d' => 'Death rates rise due to famine',
        'correct_option' => 'B',
        'explanation' => 'This stage represents the "population explosion" seen in many developing nations.'
    ],
    [
        'question_text' => "'Agglomeration economies' refer to the benefits firms gain by:",
        'option_a' => 'Moving to rural areas',
        'option_b' => 'Locating near each other in a single cluster',
        'option_c' => 'Diversifying their products',
        'option_d' => 'Reducing their workforce',
        'correct_option' => 'B',
        'explanation' => 'Clustering allows for shared infrastructure, specialized labor pools, and lower costs.'
    ],
    [
        'question_text' => 'The most extensive agricultural system practiced in the Northern Savanna of Nigeria is:',
        'option_a' => 'Plantation agriculture',
        'option_b' => 'Mediterranean farming',
        'option_c' => 'Nomadic herding',
        'option_d' => 'Intensive subsistence farming',
        'correct_option' => 'C',
        'explanation' => 'Vast grasslands and a seasonal climate favor the movement of livestock (transhumance).'
    ],
    [
        'question_text' => "Which Nigerian city is best known for 'Groundnut Pyramids' in the past?",
        'option_a' => 'Ibadan',
        'option_b' => 'Kano',
        'option_c' => 'Enugu',
        'option_d' => 'Port Harcourt',
        'correct_option' => 'B',
        'explanation' => 'Kano was the historic hub for groundnut production and trade in Northern Nigeria.'
    ],
    [
        'question_text' => 'The Great Lakes of North America are an important waterway for:',
        'option_a' => 'Coffee and Cocoa',
        'option_b' => 'Iron ore and Wheat',
        'option_c' => 'Rubber and Timber',
        'option_d' => 'Crude oil only',
        'correct_option' => 'B',
        'explanation' => 'The St. Lawrence Seaway connects the industrial heartland (iron) and the prairies (wheat) to the Atlantic.'
    ],
    [
        'question_text' => "In which ecological zone of Nigeria is 'Lumbering' a major economic activity?",
        'option_a' => 'Sudan Savanna',
        'option_b' => 'Tropical Rainforest',
        'option_c' => 'Sahel Savanna',
        'option_d' => 'Montane vegetation',
        'correct_option' => 'B',
        'explanation' => 'High rainfall supports large hardwood trees like Iroko and Mahogany.'
    ],
    [
        'question_text' => "The 'Aswan High Dam' is located on which river?",
        'option_a' => 'River Zambezi',
        'option_b' => 'River Niger',
        'option_c' => 'River Nile',
        'option_d' => 'River Limpopo',
        'correct_option' => 'C',
        'explanation' => 'Built in Egypt to control flooding and provide hydroelectric power and irrigation.'
    ],
    [
        'question_text' => "Which of the following settlement types is typical of a 'Gap Town'?",
        'option_a' => 'A town at a river confluence',
        'option_b' => 'A town located in a pass through a mountain range',
        'option_c' => 'A town centered around a market',
        'option_d' => 'A town on a hilltop for defense',
        'correct_option' => 'B',
        'explanation' => 'Gap towns develop where transport routes are forced through a physical break in a ridge or mountain.'
    ],
    [
        'question_text' => "A 'linear' settlement pattern is most likely to develop along:",
        'option_a' => 'A river delta',
        'option_b' => 'A railway line or highway',
        'option_c' => 'A high-altitude plateau',
        'option_d' => 'A desert oasis',
        'correct_option' => 'B',
        'explanation' => 'Buildings are arranged in a line following the path of a transport route.'
    ],
    [
        'question_text' => 'Contour lines that are very close together on a map indicate:',
        'option_a' => 'A gentle slope',
        'option_b' => 'A steep slope',
        'option_c' => 'A valley floor',
        'option_d' => 'A plateau',
        'correct_option' => 'B',
        'explanation' => 'The closer the lines, the faster the elevation changes over a short horizontal distance.'
    ],
    [
        'question_text' => 'The Sphere of Influence of a city refers to:',
        'option_a' => 'Its political boundaries',
        'option_b' => 'The area from which it draws customers and provides services',
        'option_c' => 'The distance people can walk in an hour',
        'option_d' => 'Its industrial output',
        'correct_option' => 'B',
        'explanation' => 'Also known as the hinterland, it is the geographic area served by the city\'s functions.'
    ],
    [
        'question_text' => 'Which map projection is best for maintaining the correct shape of small areas?',
        'option_a' => 'Conical',
        'option_b' => 'Cylindrical (Mercator)',
        'option_c' => 'Azimuthal',
        'option_d' => 'Conformal',
        'correct_option' => 'D',
        'explanation' => 'Conformal projections (like Mercator) preserve angles and shapes of small features.'
    ],
    [
        'question_text' => "'Pangaea' refers to:",
        'option_a' => 'The movement of tides',
        'option_b' => 'An ancient supercontinent',
        'option_c' => 'A type of volcanic rock',
        'option_d' => 'Deep-sea trenches',
        'correct_option' => 'B',
        'explanation' => 'Alfred Wegener proposed that all continents were once joined in a single landmass called Pangaea.'
    ],
    [
        'question_text' => "An 'Ox-bow lake' is a landform of:",
        'option_a' => 'River deposition and erosion',
        'option_b' => 'Wind deflation',
        'option_c' => 'Glacial abrasion',
        'option_d' => 'Marine transgression',
        'correct_option' => 'A',
        'explanation' => 'It forms when a river meander is cut off from the main channel during a flood.'
    ],
    [
        'question_text' => 'The Epicenter of an earthquake is:',
        'option_a' => 'The point deep inside the Earth where the break occurs',
        'option_b' => 'The point on the Earth\'s surface directly above the focus',
        'option_c' => 'The instrument used to measure the quake',
        'option_d' => 'The scale used to measure magnitude',
        'correct_option' => 'B',
        'explanation' => 'The "Focus" is underground; the "Epicenter" is on the surface.'
    ],
    [
        'question_text' => "A 'Yardang' is a feature of wind erosion characterized by:",
        'option_a' => 'Large circular pits',
        'option_b' => 'Ridges of hard rock separated by furrows of soft rock',
        'option_c' => 'Crescent-shaped sand dunes',
        'option_d' => 'Flat-topped hills',
        'correct_option' => 'B',
        'explanation' => 'Yardangs are streamlined ridges carved by wind abrasion in desert regions.'
    ],
    [
        'question_text' => 'The Pacific Ring of Fire is best known for:',
        'option_a' => 'High solar radiation',
        'option_b' => 'Frequent volcanic and earthquake activity',
        'option_c' => 'Extensive coral reefs',
        'option_d' => 'Large oil reserves',
        'correct_option' => 'B',
        'explanation' => 'This horseshoe-shaped zone is where several tectonic plates meet and interact.'
    ],
    [
        'question_text' => "Which of these is a 'Secondary' energy source?",
        'option_a' => 'Coal',
        'option_b' => 'Natural Gas',
        'option_c' => 'Electricity',
        'option_d' => 'Sunlight',
        'correct_option' => 'C',
        'explanation' => 'Secondary sources are generated from the conversion of primary sources (like burning coal to make electricity).'
    ],
    [
        'question_text' => 'The process of Fracking is used to extract:',
        'option_a' => 'Gold',
        'option_b' => 'Shale gas and oil',
        'option_c' => 'Limestone',
        'option_d' => 'Underground water',
        'correct_option' => 'B',
        'explanation' => 'Hydraulic fracturing involves injecting fluid at high pressure into rocks to release trapped gas.'
    ],
    [
        'question_text' => "OPEC was primarily formed to:",
        'option_a' => 'Promote agricultural trade',
        'option_b' => 'Stabilize and coordinate petroleum policies of member nations',
        'option_c' => 'Fight desertification in Africa',
        'option_d' => 'Provide loans for infrastructure',
        'correct_option' => 'B',
        'explanation' => 'The Organization of the Petroleum Exporting Countries manages global oil supply and pricing.'
    ],
    [
        'question_text' => 'Which mineral is the primary raw material for the production of Aluminum?',
        'option_a' => 'Hematite',
        'option_b' => 'Bauxite',
        'option_c' => 'Cassiterite',
        'option_d' => 'Galena',
        'correct_option' => 'B',
        'explanation' => 'Bauxite is the main ore of aluminum.'
    ],
    [
        'question_text' => 'Thermal inversion occurs when:',
        'option_a' => 'Temperature increases with altitude',
        'option_b' => 'Temperature decreases with altitude',
        'option_c' => 'It rains during the dry season',
        'option_d' => 'Winds blow from sea to land',
        'correct_option' => 'A',
        'explanation' => 'Usually, air cools as it rises; an inversion traps cool air (and pollution) near the ground under a layer of warm air.'
    ],
]);

foreach ($rows as $row) {
    // skip duplicates if already exist
    $exists = Question::where('subject_id', $subject->id)
        ->where('question_text', $row['question_text'])
        ->exists();
    if ($exists) {
        echo "skipped duplicate: " . substr($row['question_text'], 0, 60) . "...\n";
        continue;
    }

    Question::create(array_merge($row, [
        'subject_id' => $subject->id,
        'difficulty_level' => 'medium',
    ]));
    echo "inserted: " . substr($row['question_text'], 0, 60) . "...\n";
}

$count = Question::where('subject_id', $subject->id)->count();
echo "Done loading geography questions. total now: {$count}\n";
