<?php

$projectRoot = dirname(__DIR__);
require $projectRoot . '/vendor/autoload.php';

$app = require_once $projectRoot . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Subject;
use App\Models\Question;

$subject = Subject::firstOrCreate(['name' => 'CHEMISTRY']);

$rows = [
    ['question_text' => 'A sample of gas occupies 400 mL at 27°C. At what temperature would the volume be doubled if the pressure remains constant?',
     'option_a' => '327°C',
     'option_b' => '327 K',
     'option_c' => '627°C',
     'option_d' => '54°C',
     'correct_option' => 'B',
     'explanation' => 'You must use Kelvin. T₁/V₁ = T₂/V₂. If Volume doubles (V₂ = 2V₁), then T₂ = 2T₁ = 2(300) = 600 K. Convert back: 600 - 273 = 327°C. The "trap" is picking 327°C as direct answer.'],
    ['question_text' => 'In the electrolysis of dilute H₂SO₄ using platinum electrodes, the volume of gas liberated at the anode is 10 mL. What is the volume of gas liberated at the cathode?',
     'option_a' => '5 mL',
     'option_b' => '10 mL',
     'option_c' => '20 mL',
     'option_d' => '40 mL',
     'correct_option' => 'C',
     'explanation' => 'In water electrolysis (2H₂O → 2H₂ + O₂), Oxygen is at the anode and Hydrogen at the cathode. The ratio is H₂:O₂ = 2:1. If O₂ is 10, H₂ must be 20.'],
    ['question_text' => 'An organic compound C reacts with sodium metal to liberate hydrogen gas but does not give a brick-red precipitate with Fehling\'s solution. C is likely:',
     'option_a' => 'An Alkanol',
     'option_b' => 'An Alkanal',
     'option_c' => 'An Alkanone',
     'option_d' => 'An Alkanoic acid',
     'correct_option' => 'A',
     'explanation' => 'Alkanols react with Sodium to form alkoxides and H₂. Since it fails the Fehling\'s test, it isn\'t an Alkanal (aldehyde).'],
    ['question_text' => 'Which of the following pairs of gases will diffuse at the same rate? (Molar mass: H₂=2, N₂=28, CO=28, O₂=32, NO=30)',
     'option_a' => 'H₂ and O₂',
     'option_b' => 'N₂ and CO',
     'option_c' => 'CO and NO',
     'option_d' => 'NO and O₂',
     'correct_option' => 'B',
     'explanation' => 'According to Graham\'s Law, gases with the same molar mass diffuse at the same rate. Both N₂ (28) and CO (28) have a molar mass of 28.'],
    ['question_text' => 'If the solubility of a salt is 50 g per 250 mL of water at 25°C, what mass of the salt is required to saturate 1000 mL of water? (Molar mass = 100 g/mol)',
     'option_a' => '50 g',
     'option_b' => '200 g',
     'option_c' => '100 g',
     'option_d' => '250 g',
     'correct_option' => 'B',
     'explanation' => '50 g is in 250 mL. In 1000 mL (which is 4 × 250 mL), there are 4 × 50 = 200 g. Mass = 200 g.'],
    ['question_text' => 'The pH of a 0.001 M solution of a strong monobasic acid is:',
     'option_a' => '1',
     'option_b' => '2',
     'option_c' => '3',
     'option_d' => '4',
     'correct_option' => 'C',
     'explanation' => '[H⁺] = 0.001 = 10⁻³. pH = -log(10⁻³) = 3.'],
    ['question_text' => 'A certain hydrocarbon contains 80% Carbon. Its empirical formula is:',
     'option_a' => 'CH',
     'option_b' => 'CH₂',
     'option_c' => 'CH₄',
     'option_d' => 'C₂H',
     'correct_option' => 'C',
     'explanation' => 'C = 80/12 = 6.67; H = 20/1 = 20. Ratio = 6.67:20 = 1:3. So, CH₃.'],
    ['question_text' => 'Which of the following will decrease the rate of the reaction 2NO₂ ⇌ N₂O₄ (exothermic)?',
     'option_a' => 'Increasing the concentration of NO₂',
     'option_b' => 'Increasing the pressure',
     'option_c' => 'Increasing the temperature',
     'option_d' => 'Adding a catalyst',
     'correct_option' => 'C',
     'explanation' => 'The reaction is exothermic. According to Le Chatelier\'s Principle, increasing temperature shifts the equilibrium to the left, favoring the reverse reaction.'],
    ['question_text' => 'The electronic configuration of an ion X²⁺ is 1s²2s²2p⁶3s²3p⁶. The atomic number of X is:',
     'option_a' => '16',
     'option_b' => '18',
     'option_c' => '20',
     'option_d' => '22',
     'correct_option' => 'C',
     'explanation' => 'The ion has 18 electrons. Since it has a 2+ charge, it lost 2 electrons. The neutral atom had 18 + 2 = 20 electrons.'],
    ['question_text' => 'When Cl₂ is bubbled into an acidified solution of KMnO₄, the color change observed is:',
     'option_a' => 'Purple to colorless',
     'option_b' => 'Orange to green',
     'option_c' => 'Colorless to pink',
     'option_d' => 'Blue to red',
     'correct_option' => 'B',
     'explanation' => 'MnO₄⁻ is an oxidizing agent (orange) that gets reduced to Mn²⁺ ions (green) by the Cl⁻.'],
    ['question_text' => 'How many isomers are possible for the compound with the molecular formula C₄H₁₀?',
     'option_a' => '2',
     'option_b' => '3',
     'option_c' => '4',
     'option_d' => '5',
     'correct_option' => 'A',
     'explanation' => 'For Butane, the isomers are n-butane and isobutane (2-methylpropane).'],
    ['question_text' => 'Which of the following compounds will undergo addition reaction with bromine water?',
     'option_a' => 'Ethane',
     'option_b' => 'Ethanol',
     'option_c' => 'Ethene',
     'option_d' => 'Ethanoic acid',
     'correct_option' => 'C',
     'explanation' => 'Addition reactions are characteristic of unsaturated hydrocarbons (alkenes/alkynes) like Ethene.'],
    ['question_text' => 'The conjugate base of H₂SO₄ is:',
     'option_a' => 'SO₄²⁻',
     'option_b' => 'HSO₄⁻',
     'option_c' => 'SO₃',
     'option_d' => 'H₃SO₄⁺',
     'correct_option' => 'B',
     'explanation' => 'A conjugate base is formed by removing one proton (H⁺). Removing H⁺ from H₂SO₄ leaves HSO₄⁻.'],
    ['question_text' => 'In the reaction Cu + 4HNO₃(dilute) → Cu(NO₃)₂ + 2NO₂ + 2H₂O, Nitric acid acts as:',
     'option_a' => 'A reducing agent',
     'option_b' => 'A dehydrating agent',
     'option_c' => 'An oxidizing agent',
     'option_d' => 'A catalyst',
     'correct_option' => 'C',
     'explanation' => 'Nitrogen\'s oxidation state changes from +5 to +4 (reduction), meaning HNO₃ is the oxidizing agent.'],
    ['question_text' => 'A current of 2 A was passed through a solution of CuSO₄ for 32 minutes 10 seconds. The mass of copper deposited is? (Cu = 64, F = 96500 C/mol)',
     'option_a' => '4.2 g',
     'option_b' => '6.4 g',
     'option_c' => '8.3 g',
     'option_d' => '12.8 g',
     'correct_option' => 'A',
     'explanation' => 'Charge = 2 × (32 × 60 + 10) = 3870 C. Cu²⁺ deposits 64/2 = 32 g per 96500 C. 3870/96500 will deposit 2 × 32 × 3870/96500 = 4.2 g.'],
    ['question_text' => 'Which of the following salts will produce a gas that relights a glowing splint when heated?',
     'option_a' => 'KNO₃',
     'option_b' => 'NaCl',
     'option_c' => 'KCl',
     'option_d' => 'NaNO₃',
     'correct_option' => 'A',
     'explanation' => 'Alkali metal nitrates like KNO₃ decompose to give Oxygen (O₂), which supports combustion.'],
    ['question_text' => 'The geometric shape of a water molecule is:',
     'option_a' => 'Linear',
     'option_b' => 'Tetrahedral',
     'option_c' => 'V-shaped (Bent)',
     'option_d' => 'Trigonal planar',
     'correct_option' => 'C',
     'explanation' => 'Due to the two lone pairs of electrons on Oxygen, the VSEPR theory predicts a bent or V-shape.'],
    ['question_text' => 'Which of these is the most effective way to protect an underground iron pipe from rusting?',
     'option_a' => 'Painting',
     'option_b' => 'Greasing',
     'option_c' => 'Cathodic protection (Sacrificial protection)',
     'option_d' => 'Alloying',
     'correct_option' => 'C',
     'explanation' => 'For underground pipes, connecting them to a more reactive metal (like Magnesium) is the most technical and effective method.'],
    ['question_text' => 'An aqueous solution of FeCl₃ is acidic because:',
     'option_a' => 'Iron is a metal',
     'option_b' => 'Chloride is a strong acid radical',
     'option_c' => 'The salt undergoes hydrolysis',
     'option_d' => 'It contains free Fe³⁺ ions',
     'correct_option' => 'C',
     'explanation' => 'Salt hydrolysis of a salt from a weak base and strong acid produces an acidic solution.'],
    ['question_text' => 'The number of isomers for C₃H₈O is:',
     'option_a' => '1',
     'option_b' => '2',
     'option_c' => '3',
     'option_d' => '4',
     'correct_option' => 'C',
     'explanation' => 'Propan-1-ol, Propan-2-ol, and Methoxyethane (ethyl methyl ether).'],
    ['question_text' => 'Which of the following is used as a refrigerant in refrigerators?',
     'option_a' => 'Liquid Nitrogen',
     'option_b' => 'Compressed Ammonia',
     'option_c' => 'Carbon dioxide',
     'option_d' => 'Helium',
     'correct_option' => 'B',
     'explanation' => 'Ammonia has a high latent heat of vaporization, making it an excellent refrigerant.'],
    ['question_text' => 'The standard electrode potential for the reaction Zn²⁺ + 2e⁻ → Zn is -0.76 V. This negative value implies:',
     'option_a' => 'Zinc is easily reduced',
     'option_b' => 'Zinc is a strong oxidizing agent',
     'option_c' => 'Zinc is more reactive than Hydrogen',
     'option_d' => 'Zinc is a noble metal',
     'correct_option' => 'C',
     'explanation' => 'A negative standard potential means the metal is more likely to lose electrons than Hydrogen.'],
    ['question_text' => 'The main ore of aluminum is:',
     'option_a' => 'Hematite',
     'option_b' => 'Bauxite',
     'option_c' => 'Cassiterite',
     'option_d' => 'Galena',
     'correct_option' => 'B',
     'explanation' => 'Aluminum is extracted from Bauxite using the Hall-Héroult process.'],
    ['question_text' => 'When an atom undergoes Beta (β⁻) decay, its atomic number:',
     'option_a' => 'Decreases by 2',
     'option_b' => 'Increases by 1',
     'option_c' => 'Remains the same',
     'option_d' => 'Decreases by 1',
     'correct_option' => 'B',
     'explanation' => 'In β⁻-decay, a neutron turns into a proton and an electron. Since a proton is added, the atomic number increases.'],
    ['question_text' => 'Which of the following is a condensation polymer?',
     'option_a' => 'Polyethene',
     'option_b' => 'Polystyrene',
     'option_c' => 'Nylon-6,6',
     'option_d' => 'Polyvinyl chloride (PVC)',
     'correct_option' => 'C',
     'explanation' => 'Nylon-6,6 is formed by the reaction of two different monomers with the elimination of water.'],
];

foreach ($rows as $row) {
    // skip duplicates if already exist
    $exists = Question::where('subject_id', $subject->id)
        ->where('question_text', $row['question_text'])
        ->exists();
    if ($exists) {
        echo "skipped duplicate: " . substr($row['question_text'], 0, 60) . "...\n";
        continue;
    }

    Question::create(array_merge($row, [
        'subject_id' => $subject->id,
        'difficulty_level' => 'medium',
    ]));
    echo "inserted: " . substr($row['question_text'], 0, 60) . "...\n";
}

$count = Question::where('subject_id', $subject->id)->count();
echo "Done loading chemistry questions. total now: {$count}\n";
