<?php

$projectRoot = dirname(__DIR__);
require $projectRoot . '/vendor/autoload.php';

$app = require_once $projectRoot . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Subject;
use App\Models\Question;

$subject = Subject::firstOrCreate(['name' => 'BIOLOGY']);

$rows = [
    ['question_text' => 'In a DNA molecule, if Cytosine makes up 30% of the nitrogenous bases, what is the percentage of Adenine?',
     'option_a' => '20%',
     'option_b' => '30%',
     'option_c' => '40%',
     'option_d' => '70%',
     'correct_option' => 'A',
     'explanation' => 'According to Chargaff\'s Rule, A=T and G=C. If C=30%, then G=30% (Total 60%). The remaining 40% is shared equally between A and T, so A=20%.'],
    ['question_text' => 'Which of the following processes occurs during the "Dark Reaction" (Calvin Cycle) of photosynthesis?',
     'option_a' => 'Photolysis of water',
     'option_b' => 'Release of Oxygen',
     'option_c' => 'Fixation of Carbon (IV) Oxide',
     'option_d' => 'Formation of ATP from ADP',
     'correct_option' => 'C',
     'explanation' => 'The Calvin Cycle uses ATP and NADPH from the light stage to "fix" CO2 into glucose. The other options are light-dependent.'],
    ['question_text' => 'A person with blood group O can receive blood from which of the following?',
     'option_a' => 'Group A only',
     'option_b' => 'Group B only',
     'option_c' => 'Group AB only',
     'option_d' => 'Group O only',
     'correct_option' => 'D',
     'explanation' => 'While Group O is a universal donor, they can only receive from O because their plasma contains both anti-A and anti-B antibodies.'],
    ['question_text' => 'In the human kidney, the process of "Ultrafiltration" occurs specifically in the:',
     'option_a' => 'Loop of Henle',
     'option_b' => 'Proximal Convoluted Tubule',
     'option_c' => 'Bowman\'s Capsule',
     'option_d' => 'Collecting Duct',
     'correct_option' => 'C',
     'explanation' => 'High pressure in the glomerulus forces small molecules into the Bowman\'s capsule.'],
    ['question_text' => 'Which of the following is an example of "discontinuous variation" in humans?',
     'option_a' => 'Height',
     'option_b' => 'Skin color',
     'option_c' => 'Fingerprints',
     'option_d' => 'Weight',
     'correct_option' => 'C',
     'explanation' => 'Discontinuous variation has distinct categories (like blood groups or fingerprints) with no intermediates, unlike height which is continuous.'],
    ['question_text' => 'The enzyme "Rennin" is found in the gastric juice of infants to:',
     'option_a' => 'Digest proteins to peptides',
     'option_b' => 'Curdle milk by converting caseinogen to casein',
     'option_c' => 'Emulsify fats for easier digestion',
     'option_d' => 'Kill bacteria in the stomach',
     'correct_option' => 'B',
     'explanation' => 'Rennin (Chymosin) slows down the passage of milk through the stomach by curdling it, allowing for better protein digestion.'],
    ['question_text' => 'In a cross between a heterozygous tall plant (Tt) and a short plant (tt), what is the probability of producing a tall plant?',
     'option_a' => '25%',
     'option_b' => '50%',
     'option_c' => '75%',
     'option_d' => '100%',
     'correct_option' => 'B',
     'explanation' => 'A Punnett square (Tt x tt) results in 50% Tt (tall) and 50% tt (short).'],
    ['question_text' => 'Which of the following hormonal imbalances leads to "Diabetes Insipidus"?',
     'option_a' => 'Deficiency of Insulin',
     'option_b' => 'Deficiency of ADH (Vasopressin)',
     'option_c' => 'Excess of Thyroxine',
     'option_d' => 'Deficiency of Adrenaline',
     'correct_option' => 'B',
     'explanation' => 'Diabetes Insipidus is caused by a lack of Antidiuretic Hormone (ADH), leading to excessive dilute urine. Note: Insulin deficiency causes Diabetes Mellitus.'],
    ['question_text' => 'The movement of a plant shoot towards light is known as "Positive Phototropism." This is caused by:',
     'option_a' => 'Equal distribution of auxins',
     'option_b' => 'Migration of auxins to the shaded side of the shoot',
     'option_c' => 'Migration of auxins to the illuminated side',
     'option_d' => 'Destruction of auxins by sunlight',
     'correct_option' => 'B',
     'explanation' => 'Auxins accumulate on the dark side, causing those cells to elongate faster, which bends the plant toward the light.'],
    ['question_text' => 'Which part of the mammalian brain is responsible for "muscular coordination and balance"?',
     'option_a' => 'Cerebrum',
     'option_b' => 'Medulla Oblongata',
     'option_c' => 'Cerebellum',
     'option_d' => 'Hypothalamus',
     'correct_option' => 'C',
     'explanation' => 'The Cerebellum controls fine motor skills and posture.'],
    ['question_text' => 'The conversion of Ammonia to Nitrites and then to Nitrates by bacteria is called:',
     'option_a' => 'Nitrogen fixation',
     'option_b' => 'Nitrification',
     'option_c' => 'Denitrification',
     'option_d' => 'Putrefaction',
     'correct_option' => 'B',
     'explanation' => 'Nitrification is carried out by Nitrosomonas and Nitrobacter in the soil.'],
    ['question_text' => 'In which of the following organisms does "Amoeboid movement" occur?',
     'option_a' => 'Paramecium',
     'option_b' => 'Euglena',
     'option_c' => 'White blood cells',
     'option_d' => 'Spirogyra',
     'correct_option' => 'C',
     'explanation' => 'Human White Blood Cells (Leukocytes) use pseudopodia to move toward infections, similar to Amoeba.'],
    ['question_text' => 'Which of the following is a "Vestigial Organ" in humans?',
     'option_a' => 'Spleen',
     'option_b' => 'Appendix',
     'option_c' => 'Gallbladder',
     'option_d' => 'Pancreas',
     'correct_option' => 'B',
     'explanation' => 'Vestigial organs are structures that have lost their original ancestral function.'],
    ['question_text' => 'During "Anaerobic Respiration" in yeast, the products formed are:',
     'option_a' => 'Lactic acid and energy',
     'option_b' => 'Ethanol, CO2, and energy',
     'option_c' => 'Water, CO2, and energy',
     'option_d' => 'Pyruvic acid only',
     'correct_option' => 'B',
     'explanation' => 'This process is called fermentation. In humans (muscles), it produces Lactic acid instead.'],
    ['question_text' => 'The primary function of the "Lenticels" in a woody stem is:',
     'option_a' => 'Transpiration',
     'option_b' => 'Gaseous exchange',
     'option_c' => 'Protection against pests',
     'option_d' => 'Support',
     'correct_option' => 'B',
     'explanation' => 'Lenticels act as pores for gas exchange in the bark of woody plants.'],
    ['question_text' => 'Which of the following is a symptom of "Nitrogen deficiency" in plants?',
     'option_a' => 'Yellowing of leaves (Chlorosis)',
     'option_b' => 'Purple tint on leaves',
     'option_c' => 'Premature falling of fruit',
     'option_d' => 'Weak, spindly stems',
     'correct_option' => 'A',
     'explanation' => 'Nitrogen is essential for chlorophyll formation; without it, leaves turn yellow.'],
    ['question_text' => 'What is the dental formula of an adult human?',
     'option_a' => '2-1-2-3/2-1-2-3',
     'option_b' => '2-1-2-3/2-1-2-3 × 2',
     'option_c' => '1-1-2-3/1-1-2-3',
     'option_d' => '2-2-2-3/2-2-2-3 × 2',
     'correct_option' => 'B',
     'explanation' => 'This represents 32 teeth in total (2-1-2-3 per quadrant; × 4 sides).'],
    ['question_text' => 'The relationship between a "Hermit Crab" and a "Sea Anemone" is best described as:',
     'option_a' => 'Parasitism',
     'option_b' => 'Commensalism',
     'option_c' => 'Mutualism',
     'option_d' => 'Predation',
     'correct_option' => 'C',
     'explanation' => 'In this symbiotic relationship, the crab gets protection and the anemone gets food scraps and mobility.'],
    ['question_text' => 'Which of these is NOT a function of the mammalian Liver?',
     'option_a' => 'Deamination of excess amino acids',
     'option_b' => 'Storage of Iron',
     'option_c' => 'Production of digestive enzymes like Amylase',
     'option_d' => 'Detoxification of drugs',
     'correct_option' => 'C',
     'explanation' => 'Amylase is produced by the salivary glands and the pancreas, not the liver.'],
    ['question_text' => 'In the ear, the "Eustachian Tube" functions to:',
     'option_a' => 'Transmit sound vibrations to the brain',
     'option_b' => 'Equalize air pressure on both sides of the eardrum',
     'option_c' => 'Control body balance',
     'option_d' => 'Amplify sound waves',
     'correct_option' => 'B',
     'explanation' => 'The Eustachian tube connects the middle ear to the pharynx to balance pressure.'],
    ['question_text' => 'The order of the stages in "Complete Metamorphosis" is:',
     'option_a' => 'Egg → Nymph → Adult',
     'option_b' => 'Egg → Larva → Pupa → Adult',
     'option_c' => 'Egg → Pupa → Larva → Adult',
     'option_d' => 'Larva → Egg → Pupa → Adult',
     'correct_option' => 'B',
     'explanation' => 'Complete metamorphosis (seen in butterflies/houseflies) must include the pupa stage.'],
    ['question_text' => 'The "Haversian System" is a structural unit found in:',
     'option_a' => 'Cartilage',
     'option_b' => 'Bone',
     'option_c' => 'Muscle',
     'option_d' => 'Nerve tissue',
     'correct_option' => 'B',
     'explanation' => 'The Haversian system (Osteon) allows blood vessels to supply nutrients to bone cells.'],
    ['question_text' => 'Which part of the flower develops into the "Fruit" after fertilization?',
     'option_a' => 'Ovule',
     'option_b' => 'Anther',
     'option_c' => 'Ovary',
     'option_d' => 'Style',
     'correct_option' => 'C',
     'explanation' => 'The Ovary becomes the fruit, while the ovule becomes the seed.'],
    ['question_text' => 'A solution that has a higher osmotic pressure than the cell sap is said to be:',
     'option_a' => 'Isotonic',
     'option_b' => 'Hypotonic',
     'option_c' => 'Hypertonic',
     'option_d' => 'Saturated',
     'correct_option' => 'C',
     'explanation' => 'A Hypertonic solution will cause water to leave the cell, leading to plasmolysis.'],
    ['question_text' => 'The function of the "Prostate Gland" in the male reproductive system is to:',
     'option_a' => 'Produce sperm cells',
     'option_b' => 'Store sperm until ejaculation',
     'option_c' => 'Secrete an alkaline fluid to neutralize acidity in the female tract',
     'option_d' => 'Carry sperm out of the body',
     'correct_option' => 'C',
     'explanation' => 'The Prostate fluid protects sperm and increases their motility.'],
];

foreach ($rows as $row) {
    // skip duplicates if already exist
    $exists = Question::where('subject_id', $subject->id)
        ->where('question_text', $row['question_text'])
        ->exists();
    if ($exists) {
        echo "skipped duplicate: " . substr($row['question_text'], 0, 60) . "...\n";
        continue;
    }

    Question::create(array_merge($row, [
        'subject_id' => $subject->id,
        'difficulty_level' => 'hard',
    ]));
    echo "inserted: " . substr($row['question_text'], 0, 60) . "...\n";
}

$count = Question::where('subject_id', $subject->id)->count();
echo "Done loading biology questions. total now: {$count}\n";
