<?php

$projectRoot = dirname(__DIR__);
require $projectRoot . '/vendor/autoload.php';

$app = require_once $projectRoot . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Subject;
use App\Models\Question;

$subject = Subject::firstOrCreate(['name' => 'PHYSICS']);

$rows = [
    ['question_text' => 'A car accelerating from rest at 2 m/s² covers a distance of 100 m. What is its final velocity?',
     'option_a' => '10 m/s',
     'option_b' => '20 m/s',
     'option_c' => '30 m/s',
     'option_d' => '40 m/s',
     'correct_option' => 'B',
     'explanation' => 'Using v² = u² + 2as. Since it starts from rest, u = 0. v² = 0 + 2(2)(100) = 400. Therefore, v = 20 m/s.'],
    ['question_text' => 'Which of the following is a derived unit?',
     'option_a' => 'Ampere',
     'option_b' => 'Kilogram',
     'option_c' => 'Newton',
     'option_d' => 'Kelvin',
     'correct_option' => 'C',
     'explanation' => 'Ampere, Kilogram, and Kelvin are fundamental units. Newton is derived from F = ma (kg·m/s²).'],
    ['question_text' => 'The clinical thermometer is characterized by having a "constriction." What is its purpose?',
     'option_a' => 'To make the thermometer look better.',
     'option_b' => 'To prevent the mercury from flowing back too quickly.',
     'option_c' => 'To increase the sensitivity of the thermometer.',
     'option_d' => 'To prevent the mercury from freezing.',
     'correct_option' => 'B',
     'explanation' => 'The constriction ensures the mercury level stays at the peak temperature long enough for a doctor to read it before it returns to the bulb.'],
    ['question_text' => 'Calculate the work done when a force of 50 N pushes a box through a distance of 10 m at an angle of 60° to the horizontal.',
     'option_a' => '250 J',
     'option_b' => '250 J',
     'option_c' => '500 J',
     'option_d' => '866 J',
     'correct_option' => 'B',
     'explanation' => 'W = F·d·cos(θ). W = 50 × 10 × cos(60°). Since cos(60°) = 0.5, then W = 500 × 0.5 = 250 J.'],
    ['question_text' => 'The heat required to change the state of a substance without a change in temperature is called:',
     'option_a' => 'Specific heat capacity',
     'option_b' => 'Latent heat',
     'option_c' => 'Heat capacity',
     'option_d' => 'Solar heat',
     'correct_option' => 'B',
     'explanation' => 'Latent heat is "hidden" heat used to break molecular bonds during phase changes (like ice to water) at a constant temperature.'],
    ['question_text' => 'A convex mirror is used as a driving mirror because:',
     'option_a' => 'It produces an enlarged image.',
     'option_b' => 'It has a wide field of view and produces an erect image.',
     'option_c' => 'It produces a real image on a screen.',
     'option_d' => 'It converges light rays at a single point.',
     'correct_option' => 'B',
     'explanation' => 'Convex mirrors always produce diminished, erect (upright) virtual images, allowing drivers to see more of the road behind them.'],
    ['question_text' => 'An object is placed 5 cm in front of a concave mirror of focal length 10 cm. The image formed is:',
     'option_a' => 'Real and upright',
     'option_b' => 'Virtual and upright',
     'option_c' => 'Real and inverted',
     'option_d' => 'Virtual and inverted',
     'correct_option' => 'B',
     'explanation' => 'When an object is placed between the focal point and the pole of a concave mirror (u < f), the image is always virtual, upright, and magnified.'],
    ['question_text' => 'The phenomenon where white light splits into its constituent colors when passing through a prism is:',
     'option_a' => 'Refraction',
     'option_b' => 'Reflection',
     'option_c' => 'Dispersion',
     'option_d' => 'Diffraction',
     'correct_option' => 'C',
     'explanation' => 'Dispersion occurs because different colors (wavelengths) of light travel at different speeds in glass and refract at different angles.'],
    ['question_text' => 'Calculate the power of a pump that lifts 1000 kg of water through a vertical height of 10 m in 50 seconds. (Take g = 10 m/s²)',
     'option_a' => '1000 W',
     'option_b' => '2000 W',
     'option_c' => '3000 W',
     'option_d' => '5000 W',
     'correct_option' => 'B',
     'explanation' => 'P = W/t = (mgh)/t. P = (1000 × 10 × 10)/50 = 100,000/50 = 2000 W.'],
    ['question_text' => 'In a simple pendulum, the period of oscillation is independent of the:',
     'option_a' => 'Length of the string',
     'option_b' => 'Acceleration due to gravity',
     'option_c' => 'Mass of the bob',
     'option_d' => 'Location of the pendulum',
     'correct_option' => 'C',
     'explanation' => 'The formula T = 2π√(L/g) shows that the period only depends on length (L) and gravity (g), not the mass.'],
    ['question_text' => 'Which of the following materials is a good insulator?',
     'option_a' => 'Copper',
     'option_b' => 'Graphite',
     'option_c' => 'Ebonite',
     'option_d' => 'Aluminum',
     'correct_option' => 'C',
     'explanation' => 'Ebonite is a hard rubber and a non-conductor. Graphite is the only non-metal that conducts electricity.'],
    ['question_text' => 'The process of heat transfer through a vacuum is known as:',
     'option_a' => 'Conduction',
     'option_b' => 'Convection',
     'option_c' => 'Radiation',
     'option_d' => 'Evaporation',
     'correct_option' => 'C',
     'explanation' => 'Radiation does not require a material medium; it travels via electromagnetic waves (like heat from the sun).'],
    ['question_text' => 'A transformer has 200 turns in the primary and 600 turns in the secondary. If the primary voltage is 120 V, the secondary voltage is:',
     'option_a' => '40 V',
     'option_b' => '360 V',
     'option_c' => '480 V',
     'option_d' => '720 V',
     'correct_option' => 'B',
     'explanation' => 'Vs/Vp = Ns/Np. Vs/120 = 600/200 = 3. Therefore Vs = 360 V.'],
    ['question_text' => 'What is the equivalent resistance of two 6 Ω resistors connected in parallel?',
     'option_a' => '3 Ω',
     'option_b' => '6 Ω',
     'option_c' => '12 Ω',
     'option_d' => '18 Ω',
     'correct_option' => 'A',
     'explanation' => 'For identical resistors in parallel, 1/R = 1/6 + 1/6 = 2/6 = 1/3. Therefore R = 3 Ω.'],
    ['question_text' => 'The particle that is responsible for carrying a negative charge in a conductor is the:',
     'option_a' => 'Proton',
     'option_b' => 'Neutron',
     'option_c' => 'Electron',
     'option_d' => 'Ion',
     'correct_option' => 'C',
     'explanation' => 'Electrons are the mobile charge carriers in metals; protons and neutrons are fixed in the nucleus.'],
    ['question_text' => 'If the frequency of a wave is 50 Hz and its wavelength is 6 m, what is the velocity of the wave?',
     'option_a' => '200 m/s',
     'option_b' => '300 m/s',
     'option_c' => '400 m/s',
     'option_d' => '500 m/s',
     'correct_option' => 'B',
     'explanation' => 'v = f × λ. v = 50 × 6 = 300 m/s.'],
    ['question_text' => 'Which of the following electromagnetic waves has the shortest wavelength?',
     'option_a' => 'Radio waves',
     'option_b' => 'Infrared rays',
     'option_c' => 'Gamma rays',
     'option_d' => 'Ultraviolet rays',
     'correct_option' => 'C',
     'explanation' => 'Gamma rays have the highest frequency and therefore the shortest wavelength in the EM spectrum.'],
    ['question_text' => 'The escape velocity of a rocket from the Earth\'s surface depends on:',
     'option_a' => 'The mass of the rocket',
     'option_b' => 'The mass of the Earth',
     'option_c' => 'The color of the rocket',
     'option_d' => 'The time of launch',
     'correct_option' => 'B',
     'explanation' => 've = √(2GM/r). It depends on the mass of the planet (M) and its radius (r), not the mass of the object escaping.'],
    ['question_text' => 'Pressure in a liquid increases with:',
     'option_a' => 'Surface area',
     'option_b' => 'Depth',
     'option_c' => 'Volume',
     'option_d' => 'Shape of the container',
     'correct_option' => 'B',
     'explanation' => 'P = ρgh. Pressure is directly proportional to depth (h).'],
    ['question_text' => 'Which instrument is used to measure the relative density of a liquid?',
     'option_a' => 'Barometer',
     'option_b' => 'Hydrometer',
     'option_c' => 'Hygrometer',
     'option_d' => 'Thermometer',
     'correct_option' => 'B',
     'explanation' => 'Hydrometers float in liquids to determine density based on buoyancy.'],
    ['question_text' => 'A 100 W bulb is used for 5 hours. How much energy is consumed in Joules?',
     'option_a' => '500 J',
     'option_b' => '18,000 J',
     'option_c' => '1,800,000 J',
     'option_d' => '360,000 J',
     'correct_option' => 'C',
     'explanation' => 'E = P × t. Convert hours to seconds: 5 hours = 5 × 3600 = 18,000 seconds. Energy = 100 × 18,000 = 1,800,000 J.'],
    ['question_text' => 'The property of a material to return to its original shape after being stretched is:',
     'option_a' => 'Plasticity',
     'option_b' => 'Brittleness',
     'option_c' => 'Elasticity',
     'option_d' => 'Ductility',
     'correct_option' => 'C',
     'explanation' => 'Elasticity is the ability of a body to resist a distorting influence and return to its original size when the force is removed.'],
    ['question_text' => 'The image formed by a plane mirror is always:',
     'option_a' => 'Real and diminished',
     'option_b' => 'Virtual and same size as object',
     'option_c' => 'Real and magnified',
     'option_d' => 'Virtual and inverted',
     'correct_option' => 'B',
     'explanation' => 'Plane mirrors produce images that are virtual, upright, laterally inverted, and the same size as the object.'],
    ['question_text' => 'In the fusion of two light nuclei to form a heavier nucleus:',
     'option_a' => 'Energy is absorbed',
     'option_b' => 'Energy is released',
     'option_c' => 'Mass is increased',
     'option_d' => 'No change occurs',
     'correct_option' => 'B',
     'explanation' => 'Nuclear fusion releases a massive amount of energy (this is how the sun produces heat).'],
    ['question_text' => 'The resistance of a wire increases when:',
     'option_a' => 'Its length increases',
     'option_b' => 'Its diameter increases',
     'option_c' => 'Its temperature decreases',
     'option_d' => 'It is made of silver',
     'correct_option' => 'A',
     'explanation' => 'R = ρL/A. Resistance is directly proportional to length (L) and inversely proportional to cross-sectional area (A).'],
];

foreach ($rows as $row) {
    // skip duplicates if already exist
    $exists = Question::where('subject_id', $subject->id)
        ->where('question_text', $row['question_text'])
        ->exists();
    if ($exists) {
        echo "skipped duplicate: " . substr($row['question_text'], 0, 60) . "...\n";
        continue;
    }

    Question::create(array_merge($row, [
        'subject_id' => $subject->id,
        'difficulty_level' => 'medium',
    ]));
    echo "inserted: " . substr($row['question_text'], 0, 60) . "...\n";
}

$count = Question::where('subject_id', $subject->id)->count();
echo "Done loading physics questions. total now: {$count}\n";
