<?php

$projectRoot = dirname(__DIR__);
require $projectRoot . '/vendor/autoload.php';

$app = require_once $projectRoot . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Subject;
use App\Models\Question;

$subject = Subject::firstOrCreate(['name' => 'Accounting']);

$rows = [
    ['question_text' => 'Ledger accounts are mainly classified into ____',
     'option_a' => 'Nominal, real and personal accounts',
     'option_b' => 'Fixed and current accounts',
     'option_c' => 'Management, financial and public sector accounts',
     'option_d' => 'Bank and cash accounts',
     'correct_option' => 'A',
     'explanation' => 'Ledger accounts are classified into: Personal accounts (individuals, companies); Real accounts (assets like land, cash); Nominal accounts (expenses and incomes)'],
    ['question_text' => 'If salary account is debited instead of stationery account, the error is one of ____',
     'option_a' => 'Commission',
     'option_b' => 'Omission',
     'option_c' => 'Principle',
     'option_d' => 'Compensation',
     'correct_option' => 'A',
     'explanation' => 'Error of commission occurs when: Correct amount is entered but posted to the wrong account of the same class. Both salary and stationery are expenses (nominal accounts), so this is error of commission.'],
    ['question_text' => 'If stationery bought for ₦200 was entered as ₦2000, the correction is to',
     'option_a' => 'Debit stationery ₦2,200',
     'option_b' => 'Credit stationery ₦1,800',
     'option_c' => 'Debit stationery ₦1,800',
     'option_d' => 'Credit stationery ₦2,200',
     'correct_option' => 'B',
     'explanation' => 'Overstated by ₦1,800 (2000 – 200). To reduce stationery expense, we credit ₦1,800.'],
    ['question_text' => 'The account referring to tangible assets of permanent nature is',
     'option_a' => 'Personal account',
     'option_b' => 'Real account',
     'option_c' => 'Nominal account',
     'option_d' => 'Cash account',
     'correct_option' => 'B',
     'explanation' => 'Tangible permanent assets (land, building, vehicles) are Real accounts.'],
    ['question_text' => 'The major feature of an invoice is that it',
     'option_a' => 'Passes through sales day book',
     'option_b' => 'Has cash and bank column',
     'option_c' => 'Specifies goods bought',
     'option_d' => 'Indicates only cash sales',
     'correct_option' => 'C',
     'explanation' => 'An invoice provides: Description of goods; Quantity; Price; Total amount due.'],
    ['question_text' => 'Benefits enjoyed but not yet paid for are called',
     'option_a' => 'Accruals',
     'option_b' => 'Prepayments',
     'option_c' => 'Acquisitions',
     'option_d' => 'Provisions',
     'correct_option' => 'A',
     'explanation' => 'Accruals are: Expenses incurred but not yet paid. Example: unpaid salaries.'],
    ['question_text' => 'Under periodic stock system, stock is updated',
     'option_a' => 'At end of accounting year',
     'option_b' => 'Not considered',
     'option_c' => 'Continuously',
     'option_d' => 'At beginning of year',
     'correct_option' => 'A',
     'explanation' => 'Periodic system updates stock only at the end of the accounting period after physical count.'],
    ['question_text' => 'In a period of rising prices, LIFO results in',
     'option_a' => 'Higher cost of goods sold',
     'option_b' => 'Higher gross profit',
     'option_c' => 'Higher tax',
     'option_d' => 'Higher closing stock',
     'correct_option' => 'A',
     'explanation' => 'Under LIFO: Latest (more expensive) goods are issued first → COGS increases → Profit decreases.'],
    ['question_text' => 'Prime cost consists of',
     'option_a' => 'Production cost + selling expenses',
     'option_b' => 'Direct materials + direct labour + direct expenses',
     'option_c' => 'Direct materials + overhead',
     'option_d' => 'Administrative + selling expenses',
     'correct_option' => 'B',
     'explanation' => 'Prime Cost = Direct Material + Direct Labour + Direct Expenses.'],
    ['question_text' => 'Excess of income over expenditure in a club is',
     'option_a' => 'Deducted from capital',
     'option_b' => 'Added to accumulated fund',
     'option_c' => 'Added to capital',
     'option_d' => 'Deducted from accumulated fund',
     'correct_option' => 'B',
     'explanation' => 'Not-for-profit organisations use Accumulated Fund instead of capital. Surplus increases accumulated fund.'],
    ['question_text' => 'The equivalent of a club’s receipts and payments account is',
     'option_a' => 'Trading account',
     'option_b' => 'Revenue account',
     'option_c' => 'Cash account',
     'option_d' => 'Suspense account',
     'correct_option' => 'C',
     'explanation' => 'Receipts and Payments Account is simply a summary of cash transactions.'],
    ['question_text' => 'The salary of a partner is debited to',
     'option_a' => 'Sundry debtors',
     'option_b' => 'Appropriation account',
     'option_c' => 'Profit and loss account',
     'option_d' => 'Current account',
     'correct_option' => 'B',
     'explanation' => 'Partner salaries are not expenses. They are appropriation of profit → recorded in Profit & Loss Appropriation Account.'],
    ['question_text' => 'Interest on partner’s loan is',
     'option_a' => 'Debited to current account',
     'option_b' => 'Credited to P&L',
     'option_c' => 'Debited to P&L',
     'option_d' => 'Credited to current account',
     'correct_option' => 'C',
     'explanation' => 'Interest on loan is a business expense. So it is charged to Profit and Loss Account.'],
    ['question_text' => 'Shares issued above nominal value are issued at',
     'option_a' => 'Premium',
     'option_b' => 'Par',
     'option_c' => 'Discount',
     'option_d' => 'Loss',
     'correct_option' => 'A',
     'explanation' => 'If face value = ₦80 issued at ₦96 → ₦16 is Share Premium.'],
    ['question_text' => 'The financial plan of government for a year is',
     'option_a' => 'Budget',
     'option_b' => 'Cash analysis',
     'option_c' => 'Vote book',
     'option_d' => 'Gazette',
     'correct_option' => 'A',
     'explanation' => 'Budget is the government’s yearly financial plan of revenue and expenditure.'],
    ['question_text' => 'The capital contributed by partners is recorded in',
     'option_a' => 'Current account',
     'option_b' => 'Capital account',
     'option_c' => 'Trading account',
     'option_d' => 'Balance sheet',
     'correct_option' => 'B',
     'explanation' => 'Partners’ investments are recorded in Capital Account.'],
    ['question_text' => 'A typical example of real account is',
     'option_a' => 'Prepayment',
     'option_b' => 'Expense',
     'option_c' => 'Plant',
     'option_d' => 'Income',
     'correct_option' => 'C',
     'explanation' => 'Plant is a tangible fixed asset → Real Account.'],
    ['question_text' => 'Subscription paid in advance is treated as',
     'option_a' => 'Surplus',
     'option_b' => 'Liability',
     'option_c' => 'Deficit',
     'option_d' => 'Asset',
     'correct_option' => 'B',
     'explanation' => 'The club owes service → therefore it is a liability.'],
    ['question_text' => 'Work-in-progress represents',
     'option_a' => 'Value of partly finished goods',
     'option_b' => 'Value of finished goods',
     'option_c' => 'Sales minus COGS',
     'option_d' => 'Value of goods produced',
     'correct_option' => 'A',
     'explanation' => 'WIP = Goods not yet fully completed.'],
    ['question_text' => 'The founders of a company are',
     'option_a' => 'Promoters',
     'option_b' => 'Shareholders',
     'option_c' => 'Stakeholders',
     'option_d' => 'Directors',
     'correct_option' => 'A',
     'explanation' => 'Promoters are responsible for: Formation; Registration; Initial setup of the company.'],
    // additional 20 questions to reach 40 total
    ['question_text' => 'The rules governing the internal management of a partnership business are contained in a',
     'option_a' => 'Memorandum',
     'option_b' => 'Bye-law',
     'option_c' => 'Deed',
     'option_d' => 'Financial regulation',
     'correct_option' => 'C',
     'explanation' => 'The Partnership Deed contains: Profit sharing ratio; Interest on capital; Drawings; Duties of partners'],
    ['question_text' => 'The gross loss on manufacturing is transferred to the',
     'option_a' => 'Credit side of balance sheet',
     'option_b' => 'Debit side of profit and loss account',
     'option_c' => 'Credit side of profit and loss account',
     'option_d' => 'Debit side of balance sheet',
     'correct_option' => 'B',
     'explanation' => 'Gross loss reduces profit, so it is transferred to the debit side of the Profit and Loss Account.'],
    ['question_text' => 'Depreciation on a motor vehicle used for administration is charged to the',
     'option_a' => 'Manufacturing account',
     'option_b' => 'Trading account',
     'option_c' => 'Profit and Loss Account',
     'option_d' => 'Balance sheet',
     'correct_option' => 'C',
     'explanation' => 'Administrative expenses are charged to the Profit and Loss Account, not manufacturing.'],
    ['question_text' => 'The capital of a not-for-profit organization is called',
     'option_a' => 'Entity fund',
     'option_b' => 'Capital employed',
     'option_c' => 'Accumulated fund',
     'option_d' => 'Revenue reserve',
     'correct_option' => 'C',
     'explanation' => 'Clubs and societies use Accumulated Fund instead of capital.'],
    ['question_text' => 'The realization account is prepared when',
     'option_a' => 'Admitting a new partner',
     'option_b' => 'Liquidating a partnership',
     'option_c' => 'Calculating gross profit',
     'option_d' => 'Preparing trial balance',
     'correct_option' => 'B',
     'explanation' => 'Realization account is prepared during dissolution of partnership to determine profit or loss on liquidation.'],
    ['question_text' => 'The cost method of charging goods to a branch is used when',
     'option_a' => 'Goods are sent at invoice price',
     'option_b' => 'Branch stock adjustment account is used',
     'option_c' => 'Goods are sent at cost price',
     'option_d' => 'Goods are perishable',
     'correct_option' => 'C',
     'explanation' => 'Under cost method, goods are sent to branch at cost price only, without markup.'],
    ['question_text' => 'The two accounts opened in head office when goods are sent to branch are',
     'option_a' => 'Branch supplies and branch receipts',
     'option_b' => 'Branch stock account and goods sent to branch account',
     'option_c' => 'Branch stock and purchases account',
     'option_d' => 'Branch expenses and branch current account',
     'correct_option' => 'B',
     'explanation' => 'Head office maintains: Branch Stock Account; Goods Sent to Branch Account'],
    ['question_text' => 'Goodwill in partnership represents',
     'option_a' => 'Capital invested',
     'option_b' => 'Business reputation',
     'option_c' => 'Cash in bank',
     'option_d' => 'Profit reserve',
     'correct_option' => 'B',
     'explanation' => 'Goodwill = Value of reputation and customer loyalty of a business.'],
    ['question_text' => 'The document that states the objectives of a company is the',
     'option_a' => 'Articles of Association',
     'option_b' => 'Memorandum of Association',
     'option_c' => 'Prospectus',
     'option_d' => 'Certificate of incorporation',
     'correct_option' => 'B',
     'explanation' => 'Memorandum of Association defines: Company objectives; Powers; Scope of operations.'],
    ['question_text' => 'When shares are oversubscribed and excess money is returned, the entry is to debit',
     'option_a' => 'Application account',
     'option_b' => 'Share capital account',
     'option_c' => 'Cash account',
     'option_d' => 'Premium account',
     'correct_option' => 'A',
     'explanation' => 'Refund reduces the application money received → so Application Account is debited.'],
    ['question_text' => 'Investment at cost is shown in the',
     'option_a' => 'Trading account',
     'option_b' => 'Profit and loss account',
     'option_c' => 'Balance sheet',
     'option_d' => 'Cash book',
     'correct_option' => 'C',
     'explanation' => 'Investments are non-current assets → appear in the Balance Sheet.'],
    ['question_text' => 'The acid test ratio excludes',
     'option_a' => 'Cash',
     'option_b' => 'Debtors',
     'option_c' => 'Stock',
     'option_d' => 'Bank',
     'correct_option' => 'C',
     'explanation' => 'Acid Test (Quick Ratio) excludes stock because stock is not easily convertible to cash. Formula: (Current Assets – Stock) / Current Liabilities'],
    ['question_text' => 'The chief accounting officer of a local government is the',
     'option_a' => 'Chairman',
     'option_b' => 'Treasurer',
     'option_c' => 'Director',
     'option_d' => 'Auditor',
     'correct_option' => 'B',
     'explanation' => 'Treasurer manages financial records at local government level.'],
    ['question_text' => 'The major objective of departmental accounts is to',
     'option_a' => 'Share expenses',
     'option_b' => 'Compute overall profit',
     'option_c' => 'Ascertain profit of each department',
     'option_d' => 'Prepare balance sheet',
     'correct_option' => 'C',
     'explanation' => 'Departmental accounts show performance of each department separately.'],
    ['question_text' => 'Prime cost plus factory overhead equals',
     'option_a' => 'Total cost',
     'option_b' => 'Cost of goods sold',
     'option_c' => 'Production cost',
     'option_d' => 'Administrative cost',
     'correct_option' => 'C',
     'explanation' => 'Production Cost = Prime Cost + Factory Overhead.'],
    ['question_text' => 'Work-in-progress at the end of year is',
     'option_a' => 'Added to cost of goods completed',
     'option_b' => 'Deducted from cost of goods completed',
     'option_c' => 'Charged to P&L',
     'option_d' => 'Ignored',
     'correct_option' => 'B',
     'explanation' => 'Closing WIP reduces cost of goods manufactured.'],
    ['question_text' => 'Interest on drawings in partnership is',
     'option_a' => 'Expense of business',
     'option_b' => 'Income to business',
     'option_c' => 'Capital expenditure',
     'option_d' => 'Asset',
     'correct_option' => 'B',
     'explanation' => 'Interest on drawings is income to the firm because partner withdraws funds.'],
    ['question_text' => 'Share premium is classified as',
     'option_a' => 'Revenue reserve',
     'option_b' => 'Capital reserve',
     'option_c' => 'Current liability',
     'option_d' => 'Current asset',
     'correct_option' => 'B',
     'explanation' => 'Share premium is a capital reserve and not distributable as dividend.'],
    ['question_text' => 'When goods are transferred at cost plus mark-up, the difference is',
     'option_a' => 'Discount',
     'option_b' => 'Manufacturing profit',
     'option_c' => 'Sales commission',
     'option_d' => 'Expense',
     'correct_option' => 'B',
     'explanation' => 'Cost + Mark-up creates internal profit called Manufacturing Profit.'],
    ['question_text' => 'The fund into which government revenues are paid is',
     'option_a' => 'Development fund',
     'option_b' => 'Trust fund',
     'option_c' => 'Consolidated Revenue Fund',
     'option_d' => 'Capital fund',
     'correct_option' => 'C',
     'explanation' => 'All federal government revenues go into the Consolidated Revenue Fund before spending.'],
];

foreach ($rows as $row) {
    // skip duplicates if already exist
    $exists = Question::where('subject_id', $subject->id)
        ->where('question_text', $row['question_text'])
        ->exists();
    if ($exists) {
        echo "skipped duplicate: {$row['question_text']}\n";
        continue;
    }

    Question::create(array_merge($row, [
        'subject_id' => $subject->id,
        'difficulty_level' => 'easy',
    ]));
    echo "inserted: {$row['question_text']}\n";
}


$count = Question::where('subject_id', $subject->id)->count();
echo "Done loading accounting questions. total now: {$count}\n";
