<?php

$projectRoot = dirname(__DIR__);
require $projectRoot . '/vendor/autoload.php';

$app = require_once $projectRoot . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Subject;
use App\Models\Question;

$subject = Subject::firstOrCreate(['name' => 'GOVERNMENT']);

$rows = [
    ['question_text' => 'Which of the following describes the relationship between the executive and the legislature in a Parliamentary system?',
     'option_a' => 'Complete separation of powers and personnel.',
     'option_b' => 'Fusion of powers and personnel.',
     'option_c' => 'The executive is independent of the legislature.',
     'option_d' => 'The President has veto power over all bills.',
     'correct_option' => 'B',
     'explanation' => 'In a Parliamentary system, members of the executive (Cabinet) are also members of the legislature, creating a "fusion" of personnel.'],
    ['question_text' => 'The 1976 Local Government Reform in Nigeria was significant because it:',
     'option_a' => 'Abolished the traditional ruler system.',
     'option_b' => 'Introduced a uniform local government system across the country.',
     'option_c' => 'Reduced the number of local governments to 100.',
     'option_d' => 'Made local governments departments of the state ministry.',
     'correct_option' => 'B',
     'explanation' => 'Before 1976, local governments varied by region. The 1976 Reform established them as a third tier of government with uniform functions.'],
    ['question_text' => 'The principle of "Rule of Law" is often limited during a period of emergency by the use of:',
     'option_a' => 'Writ of Habeas Corpus.',
     'option_b' => 'Ouster Clauses.',
     'option_c' => 'Judicial Review.',
     'option_d' => 'Separation of Powers.',
     'correct_option' => 'B',
     'explanation' => 'Ouster clauses are legislative provisions that prevent courts from questioning the actions of the executive, thereby limiting legal accountability.'],
    ['question_text' => 'In the pre-colonial Hausa/Fulani political system, the official in charge of the treasury was the:',
     'option_a' => 'Galadima.',
     'option_b' => 'Madawaki.',
     'option_c' => 'Ma\'aji.',
     'option_d' => 'Sarki.',
     'correct_option' => 'C',
     'explanation' => 'The Ma\'aji served as the treasurer, while the Madawaki was the commander of the cavalry.'],
    ['question_text' => 'Which Nigerian constitution introduced the "Federal Character" principle?',
     'option_a' => '1960 Constitution.',
     'option_b' => '1963 Constitution.',
     'option_c' => '1979 Constitution.',
     'option_d' => '1999 Constitution.',
     'correct_option' => 'C',
     'explanation' => 'The 1979 Constitution introduced "Federal Character" to ensure equitable representation of all ethnic groups in government appointments.'],
    ['question_text' => 'A major difference between a "Pressure Group" and a "Political Party" is that the former:',
     'option_a' => 'Aims to win elections.',
     'option_b' => 'Has a wider range of objectives.',
     'option_c' => 'Seeks to influence government policy without seeking office.',
     'option_d' => 'Is always illegal in a democracy.',
     'correct_option' => 'C',
     'explanation' => 'Pressure groups lobby for specific interests, whereas political parties exist specifically to gain political power.'],
    ['question_text' => 'The "Macpherson Constitution" of 1951 was famous for introducing:',
     'option_a' => 'Absolute monarchy.',
     'option_b' => 'Semi-responsible government at the center.',
     'option_c' => 'Full self-government for the Southern region.',
     'option_d' => 'A unicameral legislature at the center.',
     'correct_option' => 'B',
     'explanation' => 'The 1951 Constitution allowed Nigerians to hold ministerial positions, though they lacked full executive control.'],
    ['question_text' => 'Which of the following is a "Residual Power" in the Nigerian Federation?',
     'option_a' => 'Defense and Security.',
     'option_b' => 'External Affairs.',
     'option_c' => 'Chieftaincy Affairs.',
     'option_d' => 'Banking and Currency.',
     'correct_option' => 'C',
     'explanation' => 'Residual powers are those not listed in the Exclusive or Concurrent lists and are reserved solely for the states.'],
    ['question_text' => 'The "Veto Power" in the United Nations Security Council is exercised by:',
     'option_a' => 'All 15 member states.',
     'option_b' => 'Only the 10 non-permanent members.',
     'option_c' => 'The 5 permanent members only.',
     'option_d' => 'The General Assembly.',
     'correct_option' => 'C',
     'explanation' => 'The P5 members (USA, UK, France, Russia, China) can block any substantive resolution.'],
    ['question_text' => '"Gerrymandering" is a practice in which:',
     'option_a' => 'Voters are bribed before elections.',
     'option_b' => 'Electoral boundaries are manipulated to favor a particular party.',
     'option_c' => 'Results are falsified at the collation center.',
     'option_d' => 'Foreigners are allowed to vote.',
     'correct_option' => 'B',
     'explanation' => 'Gerrymandering is a technical electoral tactic used to gain an unfair advantage in a first-past-the-post system.'],
    ['question_text' => 'In the pre-colonial Igbo political system, authority was largely:',
     'option_a' => 'Centralized and autocratic.',
     'option_b' => 'Decentralized and acephalous.',
     'option_c' => 'Based on hereditary succession.',
     'option_d' => 'Controlled by a single Emir.',
     'correct_option' => 'B',
     'explanation' => 'Igbo society was acephalous (stateless), where power was shared among elders, age grades, and titled men (Ozo).'],
    ['question_text' => 'The "Civil Service" is often described as "permanent" because:',
     'option_a' => 'Civil servants never retire.',
     'option_b' => 'It remains in place despite changes in government.',
     'option_c' => 'It is the highest arm of the military.',
     'option_d' => 'Its members are elected for life.',
     'correct_option' => 'B',
     'explanation' => 'This ensures continuity in public administration regardless of which political party wins an election.'],
    ['question_text' => 'Which body was responsible for the registration of political parties for the 2023 elections?',
     'option_a' => 'EFCC.',
     'option_b' => 'NPC.',
     'option_c' => 'INEC.',
     'option_d' => 'ICPC.',
     'correct_option' => 'C',
     'explanation' => 'The Independent National Electoral Commission is the sole body empowered to register parties and conduct elections in Nigeria.'],
    ['question_text' => 'The "Bolshevik Revolution" of 1917 in Russia led to the establishment of:',
     'option_a' => 'Capitalism.',
     'option_b' => 'Fascism.',
     'option_c' => 'Communism.',
     'option_d' => 'Feudalism.',
     'correct_option' => 'C',
     'explanation' => 'Led by Vladimir Lenin, it created the first socialist state, influencing global political ideologies.'],
    ['question_text' => 'The primary reason for the "Policy of Association" used by the French was to:',
     'option_a' => 'Grant independence to African colonies.',
     'option_b' => 'Respect the traditional culture and institutions of the colonies.',
     'option_c' => 'Replace African culture with French culture.',
     'option_d' => 'Form a military alliance against the British.',
     'correct_option' => 'B',
     'explanation' => 'Association was the successor to the Policy of Assimilation, acknowledging that African cultures could not be entirely erased.'],
    ['question_text' => 'Under the 1963 Republican Constitution, the Head of State was the:',
     'option_a' => 'Queen of England.',
     'option_b' => 'Prime Minister.',
     'option_c' => 'President.',
     'option_d' => 'Governor-General.',
     'correct_option' => 'C',
     'explanation' => 'The 1963 Constitution made Nigeria a Republic, replacing the Queen with a ceremonial President (Dr. Nnamdi Azikiwe).'],
    ['question_text' => '"Diplomatic Immunity" means that a foreign diplomat:',
     'option_a' => 'Can be tried for any crime in the host country.',
     'option_b' => 'Is exempt from the laws of the host country to a large extent.',
     'option_c' => 'Must pay all local taxes.',
     'option_d' => 'Is the Head of Government of his own country.',
     'correct_option' => 'B',
     'explanation' => 'Under the Vienna Convention, diplomats are protected from prosecution to ensure they can perform their duties without intimidation.'],
    ['question_text' => 'The "Ombudsman" (Public Complaints Commission) is established to:',
     'option_a' => 'Arrest criminals.',
     'option_b' => 'Protect citizens against administrative injustice and abuse of power.',
     'option_c' => 'Conduct census counts.',
     'option_d' => 'Advise the President on military matters.',
     'correct_option' => 'B',
     'explanation' => 'The Ombudsman serves as a mediator between the state and the individual to correct government errors.'],
    ['question_text' => 'The fundamental objective of "Non-Alignment" during the Cold War was to:',
     'option_a' => 'Support the Soviet Union against the USA.',
     'option_b' => 'Form a third world power bloc independent of the superpowers.',
     'option_c' => 'Join the North Atlantic Treaty Organization (NATO).',
     'option_d' => 'Abolish the United Nations.',
     'correct_option' => 'B',
     'explanation' => 'The Non-Aligned Movement was founded by countries like India, Egypt, and Yugoslavia to avoid being drawn into superpower conflicts.'],
    ['question_text' => 'Which of the following is a "Unitary State"?',
     'option_a' => 'Nigeria.',
     'option_b' => 'USA.',
     'option_c' => 'Britain.',
     'option_d' => 'Canada.',
     'correct_option' => 'C',
     'explanation' => 'In Britain, power is concentrated at the center (Westminster), unlike the federal systems of Nigeria or the USA.'],
    ['question_text' => 'The "Judicial Service Commission" is responsible for:',
     'option_a' => 'Passing laws in the state.',
     'option_b' => 'Recommending the appointment and discipline of judicial officers.',
     'option_c' => 'Defending criminals in court.',
     'option_d' => 'Managing the police force.',
     'correct_option' => 'B',
     'explanation' => 'This ensures the independence and integrity of the Judiciary.'],
    ['question_text' => 'What is the maximum number of years a Nigerian President can serve according to the 1999 Constitution?',
     'option_a' => '4 years.',
     'option_b' => '5 years.',
     'option_c' => '8 years.',
     'option_d' => '10 years.',
     'correct_option' => 'C',
     'explanation' => 'A President can serve two terms of four years each, totaling 8 years.'],
    ['question_text' => 'The "Oyo Mesi" in the Old Oyo Empire functioned as the:',
     'option_a' => 'King\'s personal bodyguards.',
     'option_b' => 'Council of State/Kingmakers.',
     'option_c' => 'Provincial governors.',
     'option_d' => 'Secret police.',
     'correct_option' => 'B',
     'explanation' => 'The Oyo Mesi acted as a check on the powers of the Alaafin and could ask him to "sleep" (commit suicide) if he became tyrannical.'],
    ['question_text' => '"Fascism" as a political ideology emphasizes:',
     'option_a' => 'Individual freedom and democracy.',
     'option_b' => 'Extreme nationalism and dictatorial power.',
     'option_c' => 'Communal ownership of land.',
     'option_d' => 'The abolition of the state.',
     'correct_option' => 'B',
     'explanation' => 'Fascism, popularized by Mussolini, suppresses opposition and promotes state interests above all else.'],
    ['question_text' => 'The term "Franchise" refers to the:',
     'option_a' => 'Right of a company to sell goods.',
     'option_b' => 'Right of a citizen to vote in an election.',
     'option_c' => 'Power of a judge to sentence a criminal.',
     'option_d' => 'Freedom of the press.',
     'correct_option' => 'B',
     'explanation' => 'Universal adult suffrage means the franchise is extended to all adults regardless of property or gender.'],
];

foreach ($rows as $row) {
    // skip duplicates if already exist
    $exists = Question::where('subject_id', $subject->id)
        ->where('question_text', $row['question_text'])
        ->exists();
    if ($exists) {
        echo "skipped duplicate: " . substr($row['question_text'], 0, 60) . "...\n";
        continue;
    }

    Question::create(array_merge($row, [
        'subject_id' => $subject->id,
        'difficulty_level' => 'hard',
    ]));
    echo "inserted: " . substr($row['question_text'], 0, 60) . "...\n";
}

$count = Question::where('subject_id', $subject->id)->count();
echo "Done loading government questions. total now: {$count}\n";
