<?php

$projectRoot = dirname(__DIR__);
require $projectRoot . '/vendor/autoload.php';

$app = require_once $projectRoot . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Subject;
use App\Models\Question;

$subject = Subject::firstOrCreate(['name' => 'ECONOMICS']);

$rows = [
    ['question_text' => 'If the price of a commodity increases from ₦10 to ₦15 and the quantity demanded remains at 50 units, the price elasticity of demand is:',
     'option_a' => 'Perfectly Elastic',
     'option_b' => 'Perfectly Inelastic',
     'option_c' => 'Unitary Elastic',
     'option_d' => 'Relatively Elastic',
     'correct_option' => 'B',
     'explanation' => 'Since quantity does not change regardless of price, the elasticity is zero, which is Perfectly Inelastic.'],
    ['question_text' => 'In a perfectly competitive market, a firm\'s marginal revenue is always equal to its:',
     'option_a' => 'Total Cost',
     'option_b' => 'Average Fixed Cost',
     'option_c' => 'Average Revenue (Price)',
     'option_d' => 'Marginal Cost',
     'correct_option' => 'C',
     'explanation' => 'In Perfect Competition, the firm is a price taker; hence MR = AR = P.'],
    ['question_text' => 'Which of the following is a "Leakage" from the circular flow of national income?',
     'option_a' => 'Investment',
     'option_b' => 'Government Spending',
     'option_c' => 'Exports',
     'option_d' => 'Savings',
     'correct_option' => 'D',
     'explanation' => 'Leakages are variables that reduce the flow of money in an economy (Savings, Taxes, Imports).'],
    ['question_text' => '"Giffen goods" are a special type of inferior goods where the:',
     'option_a' => 'Substitution effect outweighs the income effect.',
     'option_b' => 'Income effect is positive.',
     'option_c' => 'Income effect outweighs the substitution effect.',
     'option_d' => 'Demand curve is horizontal.',
     'correct_option' => 'C',
     'explanation' => 'For Giffen goods, as price rises, people buy more because the negative income effect is stronger than the substitution effect.'],
    ['question_text' => 'If the Marginal Propensity to Consume (MPC) is 0.8, what is the value of the Multiplier?',
     'option_a' => '2',
     'option_b' => '4',
     'option_c' => '5',
     'option_d' => '10',
     'correct_option' => 'C',
     'explanation' => 'Multiplier = 1/(1-MPC). So, 1/(1-0.8) = 1/0.2 = 5.'],
    ['question_text' => 'Deflationary gap occurs when:',
     'option_a' => 'Aggregate demand exceeds full employment output.',
     'option_b' => 'Aggregate demand is less than full employment output.',
     'option_c' => 'Imports are greater than exports.',
     'option_d' => 'The government runs a budget surplus.',
     'correct_option' => 'B',
     'explanation' => 'A Deflationary gap indicates that the economy is performing below its potential, leading to unemployment.'],
    ['question_text' => 'A tax system where the rate of tax increases as income increases is called:',
     'option_a' => 'Regressive Tax',
     'option_b' => 'Proportional Tax',
     'option_c' => 'Progressive Tax',
     'option_d' => 'Indirect Tax',
     'correct_option' => 'C',
     'explanation' => 'Progressive Taxation (like Nigeria\'s PAYE) aims to reduce income inequality.'],
    ['question_text' => '"Utility" in economics is best defined as:',
     'option_a' => 'The usefulness of a commodity.',
     'option_b' => 'The satisfaction derived from consuming a commodity.',
     'option_c' => 'The price of a commodity.',
     'option_d' => 'The availability of a commodity.',
     'correct_option' => 'B',
     'explanation' => 'Utility is subjective and varies from person to person.'],
    ['question_text' => 'Which of the following will lead to an "Increase in Quantity Supplied" (movement along the curve)?',
     'option_a' => 'An improvement in technology.',
     'option_b' => 'A decrease in the cost of production.',
     'option_c' => 'An increase in the price of the commodity itself.',
     'option_d' => 'A government subsidy to producers.',
     'correct_option' => 'C',
     'explanation' => 'Only a change in the price of the good itself causes a movement along the curve. Others cause a shift.'],
    ['question_text' => 'The "Production Possibility Curve" (PPC) is concave to the origin because of:',
     'option_a' => 'Diminishing Marginal Utility.',
     'option_b' => 'Increasing Opportunity Cost.',
     'option_c' => 'Decreasing Returns to Scale.',
     'option_d' => 'Constant Returns to Scale.',
     'correct_option' => 'B',
     'explanation' => 'As you produce more of one good, you must give up increasing amounts of the other good due to Resource Specialization.'],
    ['question_text' => 'A central bank uses "Open Market Operations" (OMO) to:',
     'option_a' => 'Control the exchange rate.',
     'option_b' => 'Buy and sell government securities to regulate money supply.',
     'option_c' => 'Fix the minimum wage.',
     'option_d' => 'Direct commercial banks on who to lend to.',
     'correct_option' => 'B',
     'explanation' => 'OMO is a tool of Monetary Policy used by the Central Bank of Nigeria to control inflation.'],
    ['question_text' => 'In a Monopoly, the "Deadweight Loss" represents:',
     'option_a' => 'The profit made by the monopolist.',
     'option_b' => 'The loss in social welfare due to underproduction.',
     'option_c' => 'The cost of advertising.',
     'option_d' => 'Taxes paid to the government.',
     'correct_option' => 'B',
     'explanation' => 'Deadweight loss occurs because the monopolist restricts output to keep prices high.'],
    ['question_text' => 'Which of the following is a "Normal Good"?',
     'option_a' => 'One whose demand falls as income rises.',
     'option_b' => 'One whose demand rises as income rises.',
     'option_c' => 'One whose demand is independent of income.',
     'option_d' => 'One that has no substitutes.',
     'correct_option' => 'B',
     'explanation' => 'Most goods are Normal Goods. Inferior goods are the ones whose demand falls when you get richer.'],
    ['question_text' => 'The "Law of Diminishing Marginal Returns" applies only in the:',
     'option_a' => 'Market Period.',
     'option_b' => 'Short Run.',
     'option_c' => 'Long Run.',
     'option_d' => 'Secular Period.',
     'correct_option' => 'B',
     'explanation' => 'In the Short Run, at least one factor of production (like land) is fixed.'],
    ['question_text' => 'If the cross-price elasticity of demand between two goods is negative, the goods are:',
     'option_a' => 'Substitutes.',
     'option_b' => 'Competitors.',
     'option_c' => 'Complements.',
     'option_d' => 'Independent.',
     'correct_option' => 'C',
     'explanation' => 'Complementary goods (like bread and butter) have a negative cross-price elasticity; if the price of one rises, demand for the other falls.'],
    ['question_text' => '"Real GDP" differs from "Nominal GDP" because it is adjusted for:',
     'option_a' => 'Taxes.',
     'option_b' => 'Depreciation.',
     'option_c' => 'Inflation.',
     'option_d' => 'Foreign Aid.',
     'correct_option' => 'C',
     'explanation' => 'Real GDP uses constant prices to show actual growth in output.'],
    ['question_text' => 'Which of the following is a "Fixed Cost" for a tailoring business?',
     'option_a' => 'Thread and buttons.',
     'option_b' => 'Electricity units consumed.',
     'option_c' => 'Rent for the shop.',
     'option_d' => 'Wages for daily-paid workers.',
     'correct_option' => 'C',
     'explanation' => 'Fixed Costs do not change with the level of production in the short run.'],
    ['question_text' => 'The "Paradox of Value" (Diamond-Water Paradox) was resolved by the concept of:',
     'option_a' => 'Total Utility.',
     'option_b' => 'Marginal Utility.',
     'option_c' => 'Consumer Surplus.',
     'option_d' => 'Producer Surplus.',
     'correct_option' => 'B',
     'explanation' => 'Water is essential but cheap because its Marginal Utility is low (since it is abundant).'],
    ['question_text' => 'An "Indifference Curve" shows combinations of two goods that give the consumer:',
     'option_a' => 'The same level of income.',
     'option_b' => 'The same level of satisfaction.',
     'option_c' => 'Different levels of satisfaction.',
     'option_d' => 'The maximum profit.',
     'correct_option' => 'B',
     'explanation' => 'Any point on an Indifference Curve yields the same total utility.'],
    ['question_text' => 'A "Deficit Budget" is most appropriate during a period of:',
     'option_a' => 'High Inflation.',
     'option_b' => 'Economic Recession.',
     'option_c' => 'Over-employment.',
     'option_d' => 'Rapid Economic Growth.',
     'correct_option' => 'B',
     'explanation' => 'The government spends more than it earns to stimulate demand during a slump.'],
    ['question_text' => 'Which of these is NOT a function of money?',
     'option_a' => 'Medium of exchange.',
     'option_b' => 'Store of value.',
     'option_c' => 'Measure of weight.',
     'option_d' => 'Standard for deferred payment.',
     'correct_option' => 'C',
     'explanation' => 'Money measures value/price, not physical weight.'],
    ['question_text' => 'The "Malthusian Theory" of population suggests that population grows:',
     'option_a' => 'Arithmetically.',
     'option_b' => 'Geometrically.',
     'option_c' => 'Seasonally.',
     'option_d' => 'Negatively.',
     'correct_option' => 'B',
     'explanation' => 'Malthus argued population grows geometrically while food grows arithmetically.'],
    ['question_text' => '"Stagflation" is an economic condition characterized by:',
     'option_a' => 'High inflation and high growth.',
     'option_b' => 'Low inflation and high unemployment.',
     'option_c' => 'High inflation and high unemployment.',
     'option_d' => 'Low inflation and low unemployment.',
     'correct_option' => 'C',
     'explanation' => 'Stagflation is a nightmare scenario where the economy is stagnant but prices keep rising.'],
    ['question_text' => 'The main objective of the "Economic Community of West African States" (ECOWAS) is:',
     'option_a' => 'To provide military aid.',
     'option_b' => 'To promote regional economic integration.',
     'option_c' => 'To fix the prices of oil.',
     'option_d' => 'To colonize other nations.',
     'correct_option' => 'B',
     'explanation' => 'ECOWAS aims to create a single large trading bloc in West Africa.'],
    ['question_text' => '"Opportunity Cost" is also known as:',
     'option_a' => 'Money Cost.',
     'option_b' => 'Real Cost.',
     'option_c' => 'Variable Cost.',
     'option_d' => 'Total Cost.',
     'correct_option' => 'B',
     'explanation' => 'It is the alternative forgone, representing the true sacrifice made.'],
    ['question_text' => 'Which of the following is a "Price Ceiling"?',
     'option_a' => 'A minimum price set by the government to help farmers.',
     'option_b' => 'A maximum price set by the government to protect consumers.',
     'option_c' => 'The equilibrium price in the market.',
     'option_d' => 'A tax on luxury goods.',
     'correct_option' => 'B',
     'explanation' => 'Price ceilings (like rent control) are set below the equilibrium price.'],
    ['question_text' => '"Balance of Trade" refers to the difference between the value of a country\'s:',
     'option_a' => 'Total assets and total liabilities.',
     'option_b' => 'Visible exports and visible imports.',
     'option_c' => 'Government revenue and expenditure.',
     'option_d' => 'Savings and Investment.',
     'correct_option' => 'B',
     'explanation' => 'Visible Trade only includes physical goods. Services are part of the "Balance of Payments."'],
    ['question_text' => 'In the "Law of Variable Proportions," stage II ends when:',
     'option_a' => 'Marginal Product is at its maximum.',
     'option_b' => 'Marginal Product is zero.',
     'option_c' => 'Total Product starts to fall.',
     'option_d' => 'Average Product is zero.',
     'correct_option' => 'B',
     'explanation' => 'When Marginal Product is zero, Total Product has reached its maximum.'],
    ['question_text' => 'Which of the following is an "Internal Economy of Scale"?',
     'option_a' => 'Improvement in national transport networks.',
     'option_b' => 'Use of specialized machinery by a large firm.',
     'option_c' => 'Presence of training colleges in the area.',
     'option_d' => 'Lowering of industry-wide taxes.',
     'correct_option' => 'B',
     'explanation' => 'Internal economies are advantages a single firm gains by growing larger.'],
    ['question_text' => 'If the demand for a product is "Price Elastic," a decrease in price will lead to:',
     'option_a' => 'A decrease in total revenue.',
     'option_b' => 'An increase in total revenue.',
     'option_c' => 'No change in total revenue.',
     'option_d' => 'A decrease in quantity demanded.',
     'correct_option' => 'B',
     'explanation' => 'When demand is Elastic, the percentage increase in quantity is greater than the percentage decrease in price, raising revenue.'],
];

foreach ($rows as $row) {
    // skip duplicates if already exist
    $exists = Question::where('subject_id', $subject->id)
        ->where('question_text', $row['question_text'])
        ->exists();
    if ($exists) {
        echo "skipped duplicate: " . substr($row['question_text'], 0, 60) . "...\n";
        continue;
    }

    Question::create(array_merge($row, [
        'subject_id' => $subject->id,
        'difficulty_level' => 'hard',
    ]));
    echo "inserted: " . substr($row['question_text'], 0, 60) . "...\n";
}

$count = Question::where('subject_id', $subject->id)->count();
echo "Done loading economics questions. total now: {$count}\n";
