<?php

$projectRoot = dirname(__DIR__);
require $projectRoot . '/vendor/autoload.php';

$app = require_once $projectRoot . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Subject;
use App\Models\Question;

$subject = Subject::firstOrCreate(['name' => 'Geography']);

$rows = [
    // Batch 2: Questions 11-30
    ['question_text' => 'If a football match starts in London (0°) at 4:00 PM on Saturday, what will be the time and day in a city located on longitude 180°?',
     'option_a' => '4:00 AM, Sunday',
     'option_b' => '4:00 PM, Sunday',
     'option_c' => '4:00 AM, Saturday',
     'option_d' => '6:00 AM, Sunday',
     'correct_option' => 'A',
     'explanation' => '180° difference equals 12 hours. Since the city is East of London, you add 12 hours to 4:00 PM Saturday, which results in 4:00 AM Sunday.'],
    ['question_text' => 'Which of the following processes is primarily responsible for the formation of "Exfoliation Domes" in arid regions?',
     'option_a' => 'Carbonation',
     'option_b' => 'Hydrolysis',
     'option_c' => 'Thermal Expansion',
     'option_d' => 'Oxidation',
     'correct_option' => 'C',
     'explanation' => 'In deserts, extreme temperature changes cause the outer layers of rocks to expand and contract, eventually peeling off like onion skins.'],
    ['question_text' => 'A traveler moving from the Equator toward the North Pole will notice that the vegetation changes in which specific order?',
     'option_a' => 'Tropical Rainforest → Savanna → Desert → Mediterranean',
     'option_b' => 'Savanna → Tropical Rainforest → Desert → Tundra',
     'option_c' => 'Tropical Rainforest → Desert → Savanna → Taiga',
     'option_d' => 'Desert → Savanna → Tropical Rainforest → Mediterranean',
     'correct_option' => 'A',
     'explanation' => 'Vegetation follows climatic belts; moving North from the wet Equator takes you through the drying Savanna, the arid Desert, and then the temperate Mediterranean zone.'],
    ['question_text' => 'In a settlement showing a "Linear" pattern, the most likely factor influencing its shape is the presence of:',
     'option_a' => 'A central market square',
     'option_b' => 'A fertile volcanic plain',
     'option_c' => 'A major transportation route',
     'option_d' => 'A defensive hilltop',
     'correct_option' => 'C',
     'explanation' => 'Linear settlements develop along narrow routes like roads, railways, or river banks where access to transport is primary.'],
    ['question_text' => 'Which of these atmospheric conditions is most likely to lead to the formation of "Smog" in industrial cities?',
     'option_a' => 'High wind velocity',
     'option_b' => 'Temperature Inversion',
     'option_c' => 'Convectional rainfall',
     'option_d' => 'High relative humidity',
     'correct_option' => 'B',
     'explanation' => 'Temperature inversion traps cold air (and pollutants) near the ground under a layer of warm air, preventing smoke from dispersing.'],
    ['question_text' => 'A map has a scale of 1:50,000. If the distance between two villages on the map is 10cm, what is the actual ground distance?',
     'option_a' => '0.5km',
     'option_b' => '5km',
     'option_c' => '50km',
     'option_d' => '500km',
     'correct_option' => 'B',
     'explanation' => 'Using the formula: Ground Distance = Map Distance × Scale Denominator. Since 10 cm × 50,000 = 500,000 cm = 5 km.'],
    ['question_text' => 'Which of the following is an "Internal Force" that shapes the Earth\'s crust?',
     'option_a' => 'Denudation',
     'option_b' => 'Weathering',
     'option_c' => 'Vulcanicity',
     'option_d' => 'Deposition',
     'correct_option' => 'C',
     'explanation' => 'Vulcanicity (volcanism) originates from within the Earth (endogenic), whereas the others are exogenic (external) forces.'],
    ['question_text' => 'The "Great Circle" route is preferred in long-distance aviation because it:',
     'option_a' => 'Avoids turbulent weather zones',
     'option_b' => 'Follows the lines of constant compass bearing',
     'option_c' => 'Represents the shortest distance between two points',
     'option_d' => 'Always stays within the same time zone',
     'correct_option' => 'C',
     'explanation' => 'A Great Circle is the shortest path between two points on a sphere, saving fuel and time for international flights.'],
    ['question_text' => 'Calculate the range of temperature for a station where the highest monthly temperature is 32°C and the lowest is 18°C.',
     'option_a' => '50°C',
     'option_b' => '25°C',
     'option_c' => '14°C',
     'option_d' => '10°C',
     'correct_option' => 'C',
     'explanation' => 'Temperature range is the difference between the maximum and minimum values (32 - 18 = 14°C).'],
    ['question_text' => 'Which soil type is most associated with the "Leaching" process in heavy rainfall areas like the Niger Delta?',
     'option_a' => 'Chernozem',
     'option_b' => 'Latosols (Laterites)',
     'option_c' => 'Podzols',
     'option_d' => 'Alluvial soils',
     'correct_option' => 'B',
     'explanation' => 'Heavy rain washes away nutrients (leaching), leaving behind iron and aluminum oxides that form reddish, acidic Laterite soils.'],
    ['question_text' => 'The primary reason why the population density of the Nile Valley is high despite being in a desert is:',
     'option_a' => 'Presence of mineral resources',
     'option_b' => 'Availability of water for irrigation',
     'option_c' => 'Absence of pests and diseases',
     'option_d' => 'Favorable cool climate',
     'correct_option' => 'B',
     'explanation' => 'The Nile River provides a permanent water source in an arid region, allowing for intensive agriculture.'],
    ['question_text' => 'What is the primary difference between a "Cuesta" and a "Hogback"?',
     'option_a' => 'The type of rock they are made of',
     'option_b' => 'The altitude above sea level',
     'option_c' => 'The angle of the dip slope',
     'option_d' => 'The presence of vegetation',
     'correct_option' => 'C',
     'explanation' => 'A Cuesta has one steep side and one gentle slope, while a Hogback has two equally steep sides due to a very high angle of dip.'],
    ['question_text' => 'In the theory of "Demographic Transition," a country with a high birth rate and a rapidly falling death rate is in:',
     'option_a' => 'Stage 1',
     'option_b' => 'Stage 2',
     'option_c' => 'Stage 3',
     'option_d' => 'Stage 4',
     'correct_option' => 'B',
     'explanation' => 'Stage 2 (Early Expanding) is characterized by high fertility and improving healthcare, leading to a population explosion.'],
    ['question_text' => 'Which of the following ocean currents is responsible for the fog and dry conditions along the coast of Namibia?',
     'option_a' => 'The Gulf Stream',
     'option_b' => 'The Benguela Current',
     'option_c' => 'The Canary Current',
     'option_d' => 'The Kuroshio Current',
     'correct_option' => 'B',
     'explanation' => 'The cold Benguela current cools the air above it, preventing rain and causing the formation of the Namib Desert.'],
    ['question_text' => 'The term "Karst Topography" is specifically used to describe landscapes formed in:',
     'option_a' => 'Granite rocks',
     'option_b' => 'Basaltic plateaus',
     'option_c' => 'Limestone regions',
     'option_d' => 'Sandstone ridges',
     'correct_option' => 'C',
     'explanation' => 'Karst refers to areas where the bedrock is carbonate (limestone), leading to features like sinkholes and caves through chemical weathering.'],
    ['question_text' => 'Which of the following is a "Non-renewable" natural resource?',
     'option_a' => 'Timber',
     'option_b' => 'Solar energy',
     'option_c' => 'Petroleum',
     'option_d' => 'Water',
     'correct_option' => 'C',
     'explanation' => 'Petroleum takes millions of years to form; once extracted and used, it cannot be replaced in a human timeframe.'],
    ['question_text' => 'What happens to the temperature of a parcel of air as it rises up a mountain side?',
     'option_a' => 'It increases due to pressure',
     'option_b' => 'It remains constant',
     'option_c' => 'It decreases at the adiabatic lapse rate',
     'option_d' => 'It increases due to proximity to the sun',
     'correct_option' => 'C',
     'explanation' => 'As air rises, it expands and cools. This is known as the Adiabatic Lapse Rate (approx. 6.5°C per 1,000m).'],
    ['question_text' => 'An environmental hazard common in the Sahel region of Nigeria is:',
     'option_a' => 'Oil spillage',
     'option_b' => 'Gully erosion',
     'option_c' => 'Desertification',
     'option_d' => 'Tropical cyclones',
     'correct_option' => 'C',
     'explanation' => 'The Sahel is the semi-arid transition zone where overgrazing and climate change lead to the southward encroachment of the desert.'],
    ['question_text' => 'Which type of fishing is most common in the shallow waters of the "Continental Shelf"?',
     'option_a' => 'Deep-sea trawling',
     'option_b' => 'Subsistence fishing',
     'option_c' => 'Inshore fishing',
     'option_d' => 'Sport fishing',
     'correct_option' => 'C',
     'explanation' => 'The Continental Shelf is rich in plankton and sunlight, making it the most productive area for commercial inshore fishing.'],
    ['question_text' => 'The main factor responsible for the high salinity of the Dead Sea is:',
     'option_a' => 'Excessive rainfall',
     'option_b' => 'High rate of evaporation and lack of outlets',
     'option_c' => 'Proximity to the Equator',
     'option_d' => 'Large number of rivers flowing into it',
     'correct_option' => 'B',
     'explanation' => 'In closed basins with high heat, water evaporates leaving salt behind, and because there is no outlet to the ocean, the concentration stays high.'],
    // Batch 3: Questions 31-50
    ['question_text' => 'If the RF (Representative Fraction) of a map is 1:100,000, what is the statement scale?',
     'option_a' => '1cm to 1km',
     'option_b' => '1cm to 10km',
     'option_c' => '1cm to 100km',
     'option_d' => '2cm to 1km',
     'correct_option' => 'A',
     'explanation' => '1:100,000 means 100,000 cm on ground = 1 cm on map. Therefore, 1cm on the map represents 1km on the ground.'],
    ['question_text' => 'A "U-Shaped Valley" is a landform created by the action of:',
     'option_a' => 'Running water',
     'option_b' => 'Wind erosion',
     'option_c' => 'Glacial erosion',
     'option_d' => 'Marine waves',
     'correct_option' => 'C',
     'explanation' => 'Glaciers are bulky and "bulldoze" V-shaped river valleys into wide, flat-bottomed U-shaped valleys.'],
    ['question_text' => 'The "Gutenberg Discontinuity" separates which two layers of the Earth?',
     'option_a' => 'Crust and Mantle',
     'option_b' => 'Upper Mantle and Lower Mantle',
     'option_c' => 'Mantle and Core',
     'option_d' => 'Inner Core and Outer Core',
     'correct_option' => 'C',
     'explanation' => 'The Moho separates the Crust/Mantle, while the Gutenberg separates the Mantle/Core.'],
    ['question_text' => 'Which of the following is a "Tertiary" economic activity?',
     'option_a' => 'Iron ore mining',
     'option_b' => 'Textile manufacturing',
     'option_c' => 'Banking and Finance',
     'option_d' => 'Cattle rearing',
     'correct_option' => 'C',
     'explanation' => 'Tertiary activities are service-based (Banking, Teaching, Tourism), while Primary is raw material extraction and Secondary is manufacturing.'],
    ['question_text' => 'The Mediterranean climate is characterized by:',
     'option_a' => 'Hot, wet summers and cold, dry winters',
     'option_b' => 'Hot, dry summers and mild, wet winters',
     'option_c' => 'Rainfall throughout the year',
     'option_d' => 'Extreme cold throughout the year',
     'correct_option' => 'B',
     'explanation' => 'This is a unique climate found around the Mediterranean Sea and parts of South Africa/California where rain falls in winter.'],
    ['question_text' => 'Which of the following planets has the shortest period of revolution around the sun?',
     'option_a' => 'Earth',
     'option_b' => 'Mars',
     'option_c' => 'Mercury',
     'option_d' => 'Venus',
     'correct_option' => 'C',
     'explanation' => 'Mercury is closest to the sun and travels the shortest orbital path at the highest speed.'],
    ['question_text' => 'The process by which plants release water vapor into the atmosphere is:',
     'option_a' => 'Evaporation',
     'option_b' => 'Condensation',
     'option_c' => 'Transpiration',
     'option_d' => 'Precipitation',
     'correct_option' => 'C',
     'explanation' => 'Transpiration is specifically the loss of water through the stomata of plant leaves.'],
    ['question_text' => '"Plucking" and "Abrasion" are erosional processes associated with:',
     'option_a' => 'Wind',
     'option_b' => 'Ice',
     'option_c' => 'Waves',
     'option_d' => 'Rivers',
     'correct_option' => 'B',
     'explanation' => 'Plucking occurs when ice freezes onto rock and pulls it away; abrasion is the grinding of that rock against the valley floor.'],
    ['question_text' => 'Which of these scales is the "Largest"?',
     'option_a' => '1:25,000',
     'option_b' => '1:50,000',
     'option_c' => '1:100,000',
     'option_d' => '1:250,000',
     'correct_option' => 'A',
     'explanation' => 'In map scales, the smaller the denominator, the "larger" the scale (it shows more detail of a smaller area).'],
    ['question_text' => 'The "Solar Solstice" around June 21st means the sun is vertically overhead at the:',
     'option_a' => 'Equator',
     'option_b' => 'Tropic of Cancer',
     'option_c' => 'Tropic of Capricorn',
     'option_d' => 'Arctic Circle',
     'correct_option' => 'B',
     'explanation' => 'During the Summer Solstice (Northern Hemisphere), the sun is directly above 23.5°N (Tropic of Cancer).'],
    ['question_text' => 'A major problem facing rail transport in Africa is:',
     'option_a' => 'Lack of passengers',
     'option_b' => 'Different track gauges',
     'option_c' => 'High speed of trains',
     'option_d' => 'Short distances between cities',
     'correct_option' => 'B',
     'explanation' => 'Colonial powers built railways with different widths (gauges), making it difficult to link different national rail systems.'],
    ['question_text' => 'In the "Concentric Zone Model" of city structure, the center is occupied by the:',
     'option_a' => 'Commuter zone',
     'option_b' => 'Low-class residential',
     'option_c' => 'Central Business District (CBD)',
     'option_d' => 'Industrial zone',
     'correct_option' => 'C',
     'explanation' => 'The CBD is the core of the city where commercial activity is highest.'],
    ['question_text' => 'Which of the following is a "Fold Mountain"?',
     'option_a' => 'The Drakensberg',
     'option_b' => 'The Himalayas',
     'option_c' => 'Mt. Kilimanjaro',
     'option_d' => 'The Sierra Nevada',
     'correct_option' => 'B',
     'explanation' => 'The Himalayas were formed by the collision of the Indian and Eurasian plates, folding the crust upward.'],
    ['question_text' => '"Relative Humidity" is measured using a:',
     'option_a' => 'Barometer',
     'option_b' => 'Hydrometer',
     'option_c' => 'Hygrometer',
     'option_d' => 'Anemometer',
     'correct_option' => 'C',
     'explanation' => 'A Wet and Dry bulb thermometer (Hygrometer) is used to calculate the percentage of moisture in the air.'],
    ['question_text' => 'Which of these clouds is associated with thunderstorms and heavy rain?',
     'option_a' => 'Cirrus',
     'option_b' => 'Stratus',
     'option_c' => 'Cumulonimbus',
     'option_d' => 'Altocumulus',
     'correct_option' => 'C',
     'explanation' => 'Cumulonimbus are towering vertical clouds often called "thunderheads."'],
    ['question_text' => 'The transition zone between two different ecosystems is called an:',
     'option_a' => 'Ecotone',
     'option_b' => 'Ecological niche',
     'option_c' => 'Abiotic factor',
     'option_d' => 'Biome',
     'correct_option' => 'A',
     'explanation' => 'An ecotone (like a marsh between land and lake) contains species from both systems.'],
    ['question_text' => 'The main cause of "Earth Tides" is the:',
     'option_a' => 'Rotation of the Earth',
     'option_b' => 'Gravitational pull of the Moon and Sun',
     'option_c' => 'Shifting of tectonic plates',
     'option_d' => 'Ocean currents',
     'correct_option' => 'B',
     'explanation' => 'The moon\'s gravity pulls on the Earth\'s waters, creating high and low tides.'],
    ['question_text' => 'Which of the following is a "Secondary" rock?',
     'option_a' => 'Basalt',
     'option_b' => 'Gneiss',
     'option_c' => 'Sandstone',
     'option_d' => 'Gabbro',
     'correct_option' => 'C',
     'explanation' => 'Sedimentary rocks (like sandstone) are considered "secondary" because they are formed from the debris of pre-existing rocks.'],
    ['question_text' => 'In Nigeria, the "Harmattan" wind blows from the:',
     'option_a' => 'South-West',
     'option_b' => 'North-East',
     'option_c' => 'South-East',
     'option_d' => 'North-West',
     'correct_option' => 'B',
     'explanation' => 'The North-East Trade Winds blow from the Sahara Desert, bringing dust and dry conditions.'],
    ['question_text' => 'The "Prime Meridian" passes through which of these cities?',
     'option_a' => 'New York',
     'option_b' => 'Accra',
     'option_c' => 'Cairo',
     'option_d' => 'Lagos',
     'correct_option' => 'B',
     'explanation' => 'The 0° longitude line passes through Greenwich (London) and Accra (Ghana).'],
];

foreach ($rows as $row) {
    // skip duplicates if already exist
    $exists = Question::where('subject_id', $subject->id)
        ->where('question_text', $row['question_text'])
        ->exists();
    if ($exists) {
        echo "skipped duplicate: " . substr($row['question_text'], 0, 60) . "...\n";
        continue;
    }

    Question::create(array_merge($row, [
        'subject_id' => $subject->id,
        'difficulty_level' => 'medium',
    ]));
    echo "inserted: " . substr($row['question_text'], 0, 60) . "...\n";
}

$count = Question::where('subject_id', $subject->id)->count();
echo "Done loading geography questions. total now: {$count}\n";
